In [7]:
import pandas as pd
from pandas import Series, DataFrame
import datetime as dt

def four_hour_temp(filename, date):
    
    weather_df = pd.read_csv(filename, parse_dates = [["Date", 'Time']], index_col = ['Date_Time'],
                     na_values = 'M')
    
    return weather_df.loc[date].resample('4H')['DryBulbCelsius'].mean()

In [8]:
four_hour_temp('201406hourly.txt', '2014-06-17')

C:\Users\monca016\AppData\Local\Continuum\anaconda3\envs\env_full\lib\site-packages\IPython\core\interactiveshell.py:2808: DtypeWarning: Columns (4,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

Date_Time
2014-06-17 00:00:00    17.985063
2014-06-17 04:00:00    18.546791
2014-06-17 08:00:00    23.669139
2014-06-17 12:00:00    26.177551
2014-06-17 16:00:00    24.571966
2014-06-17 20:00:00    20.548430
Freq: 4H, Name: DryBulbCelsius, dtype: float64

In [96]:
## four_hour_temp('201406hourly.txt', '2014-06-17')

import pandas as pd

from pandas import Series, DataFrame

import datetime as dt

def four_hour_temp(filename, year):
    
    fancy = pd.read_csv("fancy.dat", header = None, names = ['sales'], squeeze = True)
    dates = pd.DatetimeIndex(start = '01/01/1987', periods = len(fancy), freq = 'M')
    fancy.index = dates
    
    annual_sales = fancy.groupby(lambda x: x.year).sum()
    
    return Series(round(annual_sales.mean(), 2), index =['sales'])

In [9]:
weather = pd.read_csv("201406hourly.txt", nrows = 1000, parse_dates = [["Date", 'Time']], index_col = ['Date_Time'],
                     na_values = 'M')

In [12]:
weather.loc['2014-06-17'].resample('4H')['DryBulbCelsius'].mean().round(1)

Date_Time
2014-06-17 00:00:00    13.3
2014-06-17 04:00:00    12.5
2014-06-17 08:00:00    16.8
2014-06-17 12:00:00    18.0
2014-06-17 16:00:00    17.8
2014-06-17 20:00:00    17.0
Freq: 4H, Name: DryBulbCelsius, dtype: float64

In [45]:
weather_2  = weather['DryBulbCelsius']#.astype(float)

In [3]:
weather_2.loc['2014-06-17']

NameError: name 'weather_2' is not defined

In [15]:
weather['DryBulbCelsius'] = weather['DryBulbCelsius'].replace('M', 0.0).astype(float)

In [21]:
weather.groupby('')

,WBAN,StationType,SkyCondition,SkyConditionFlag,Visibility,VisibilityFlag,WeatherType,WeatherTypeFlag,DryBulbFarenheit,DryBulbFarenheitFlag,...,PressureChange,PressureChangeFlag,SeaLevelPressure,SeaLevelPressureFlag,RecordType,RecordTypeFlag,HourlyPrecip,HourlyPrecipFlag,Altimeter,AltimeterFlag
Date_Time,,,,,,,,,,,,,,,,,,,,,
2014-06-01 00:57:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.20,
2014-06-01 01:19:00,3011,0,SCT110,,10.0,,,,63,,...,,,M,,AA,,,,30.20,
2014-06-01 01:57:00,3011,0,SCT110,,10.0,,,,61,,...,,,M,,AA,,,,30.20,
2014-06-01 02:17:00,3011,0,SCT110,,10.0,,,,61,,...,,,M,,AA,,,,30.20,
2014-06-01 02:39:00,3011,0,BKN110,,10.0,,,,61,,...,,,M,,AA,,,,30.20,
2014-06-01 02:57:00,3011,0,BKN100,,10.0,,,,59,,...,,,M,,AA,,,,30.21,
2014-06-01 03:20:00,3011,0,BKN110,,10.0,,,,57,,...,,,M,,AA,,,,30.21,
2014-06-01 03:59:00,3011,0,OVC100,,10.0,,,,55,,...,,,M,,AA,,,,30.21,
2014-06-01 04:17:00,3011,0,OVC090,,10.0,,,,54,,...,,,M,,AA,,,,30.21,
2014-06-01 04:57:00,3011,0,BKN080,,10.0,,,,52,,...,,,M,,AA,,,,30.21,
2014-06-01 05:37:00,3011,0,SCT080,,10.0,,,,52,,...,,,M,,AA,,,,30.22,
2014-06-01 05:57:00,3011,0,CLR,,10.0,,,,52,,...,,,M,,AA,,,,30.22,
2014-06-01 06:37:00,3011,0,CLR,,10.0,,,,52,,...,,,M,,AA,,,,30.24,
2014-06-01 06:57:00,3011,0,CLR,,10.0,,,,55,,...,,,M,,AA,,,,30.24,
2014-06-01 07:37:00,3011,0,CLR,,10.0,,,,59,,...,,,M,,AA,,,,30.25,
2014-06-01 07:57:00,3011,0,CLR,,10.0,,,,59,,...,,,M,,AA,,,,30.24,
2014-06-01 08:39:00,3011,0,CLR,,10.0,,,,61,,...,,,M,,AA,,,,30.25,
2014-06-01 08:57:00,3011,0,CLR,,10.0,,,,61,,...,,,M,,AA,,,,30.24,
2014-06-01 09:17:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.24,
2014-06-01 09:37:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.25,
2014-06-01 09:57:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.25,
2014-06-01 10:20:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.25,
2014-06-01 10:37:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.25,
2014-06-01 10:57:00,3011,0,CLR,,10.0,,,,64,,...,,,M,,AA,,,,30.25,
2014-06-01 11:17:00,3011,0,CLR,,10.0,,,,64,,...,,,M,,AA,,,,30.25,
2014-06-01 11:37:00,3011,0,CLR,,10.0,,,,64,,...,,,M,,AA,,,,30.24,
2014-06-01 11:57:00,3011,0,CLR,,10.0,,,,66,,...,,,M,,AA,,,,30.24,
2014-06-01 12:19:00,3011,0,CLR,,10.0,,,,66,,...,,,M,,AA,,,,30.24,
2014-06-01 12:37:00,3011,0,CLR,,10.0,,,,66,,...,,,M,,AA,,,,30.24,
2014-06-01 13:19:00,3011,0,CLR,,10.0,,,,66,,...,,,M,,AA,,,,30.24,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-06-17 10:00:00,3011,0,CLR,,10.0,,,,61,,...,,,M,,AA,,,,30.16,
2014-06-17 11:20:00,3011,0,CLR,,10.0,,,,63,,...,,,M,,AA,,,,30.15,
2014-06-17 11:38:00,3011,0,CLR,,7.0,,,,64,,...,,,M,,AA,,,,30.14,
2014-06-17 11:59:00,3011,0,CLR,,10.0,,,,64,,...,,,M,,AA,,,,30.13,
2014-06-17 12:19:00,3011,0,CLR,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 12:38:00,3011,0,CLR,,10.0,,,,M,,...,,,M,,AA,,,,30.12,
2014-06-17 13:00:00,3011,0,CLR100,,10.0,,,,64,,...,,,M,,AA,,,,30.12,
2014-06-17 13:18:00,3011,0,SCT100,,7.0,,,,64,,...,,,M,,AA,,,,30.12,
2014-06-17 13:39:00,3011,0,BKN100,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 13:58:00,3011,0,BKN100 OVC120,,10.0,,,,64,,...,,,M,,AA,,,,30.12,
2014-06-17 14:21:00,3011,0,OVC100,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 14:38:00,3011,0,OVC100,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 14:58:00,3011,0,OVC100,,10.0,,,,64,,...,,,M,,AA,,,,30.12,
2014-06-17 15:18:00,3011,0,OVC090,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 15:38:00,3011,0,BKN090 OVC110,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 16:00:00,3011,0,BKN090 OVC110,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 16:18:00,3011,0,OVC090,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 16:38:00,3011,0,OVC090,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 16:58:00,3011,0,CLR100,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 17:38:00,3011,0,OVC100,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 17:58:00,3011,0,OVC100,,10.0,,,,64,,...,,,M,,AA,,,,30.10,
2014-06-17 18:18:00,3011,0,OVC090,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 18:38:00,3011,0,BKN100,,10.0,,,,64,,...,,,M,,AA,,,,30.11,
2014-06-17 18:59:00,3011,0,BKN100,,10.0,,,,64,,...,,,M,,AA,,,,30.12,
2014-06-17 19:18:00,3011,0,BKN100,,10.0,,,,63,,...,,,M,,AA,,,,30.12,
2014-06-17 19:38:00,3011,0,OVC100,,10.0,,,,63,,...,,,M,,AA,,,,30.12,
2014-06-17 20:20:00,3011,0,OVC100,,10.0,,,,63,,...,,,M,,AA,,,,30.13,
2014-06-17 20:38:00,3011,0,OVC100,,10.0,,,,63,,...,,,M,,AA,,,,30.14,
2014-06-17 20:58:00,3011,0,OVC100,,10.0,,,,63,,...,,,M,,AA,,,,30.15,
2014-06-17 21:18:00,3011,0,OVC100,,10.0,,,,63,,...,,,M,,AA,,,,30.14,

In [16]:
weather.loc['2014-06-17'].resample('4H')['DryBulbCelsius'].mean()

Date_Time
2014-06-17 00:00:00    13.272727
2014-06-17 04:00:00    12.545455
2014-06-17 08:00:00    16.833333
2014-06-17 12:00:00    16.363636
2014-06-17 16:00:00    17.818182
2014-06-17 20:00:00    17.000000
Freq: 4H, Name: DryBulbCelsius, dtype: float64

In [30]:
146/11

13.272727272727273

In [15]:
weather['DryBulbCelsius'].value_counts()

18.0    86
17.0    82
19.0    80
12.0    79
13.0    67
21.0    64
16.0    62
8.0     61
14.0    60
11.0    59
22.0    57
7.0     45
9.0     38
6.0     32
20.0    31
15.0    31
10.0    19
4.0     16
23.0    14
M        7
5.0      6
3.0      4
Name: DryBulbCelsius, dtype: int64

In [11]:
weather = weather[weather['DryBulbCelsius'] != 'M']
weather['DryBulbCelsius'] = weather['DryBulbCelsius'].astype(float)

In [13]:
weather['DryBulbCelsius'].astype(float).loc['2014-06-17']

Date_Time
2014-06-17 00:37:00    14.0
2014-06-17 00:57:00    14.0
2014-06-17 01:20:00    14.0
2014-06-17 01:37:00    14.0
2014-06-17 01:57:00    13.0
2014-06-17 02:20:00    13.0
2014-06-17 02:37:00    13.0
2014-06-17 02:57:00    13.0
2014-06-17 03:17:00    13.0
2014-06-17 03:37:00    13.0
2014-06-17 03:57:00    12.0
2014-06-17 04:17:00    12.0
2014-06-17 04:37:00    12.0
2014-06-17 04:57:00    12.0
2014-06-17 05:17:00    12.0
2014-06-17 05:37:00    12.0
2014-06-17 05:57:00    12.0
2014-06-17 06:17:00    12.0
2014-06-17 06:37:00    13.0
2014-06-17 06:57:00    13.0
2014-06-17 07:38:00    14.0
2014-06-17 07:57:00    14.0
2014-06-17 08:59:00    16.0
2014-06-17 09:41:00    16.0
2014-06-17 10:00:00    16.0
2014-06-17 11:20:00    17.0
2014-06-17 11:38:00    18.0
2014-06-17 11:59:00    18.0
2014-06-17 12:19:00    18.0
2014-06-17 13:00:00    18.0
2014-06-17 13:18:00    18.0
2014-06-17 13:39:00    18.0
2014-06-17 13:58:00    18.0
2014-06-17 14:21:00    18.0
2014-06-17 14:38:00    18.0
2014-06-17 14:58:00    18.0
2014-06-17 15:18:00    18.0
2014-06-17 15:38:00    18.0
2014-06-17 16:00:00    18.0
2014-06-17 16:18:00    18.0
2014-06-17 16:38:00    18.0
2014-06-17 16:58:00    18.0
2014-06-17 17:38:00    18.0
2014-06-17 17:58:00    18.0
2014-06-17 18:18:00    18.0
2014-06-17 18:38:00    18.0
2014-06-17 18:59:00    18.0
2014-06-17 19:18:00    17.0
2014-06-17 19:38:00    17.0
2014-06-17 20:20:00    17.0
2014-06-17 20:38:00    17.0
2014-06-17 20:58:00    17.0
2014-06-17 21:18:00    17.0
Name: DryBulbCelsius, dtype: float64

In [99]:
#weather['DryBulbCelsius'] != 'M'

weather.loc['2014-06-17'].resample('4H').mean()['DryBulbCelsius']

Date_Time
2014-06-17 00:00:00    13.272727
2014-06-17 04:00:00    12.545455
2014-06-17 08:00:00    16.833333
2014-06-17 12:00:00    18.000000
2014-06-17 16:00:00    17.818182
2014-06-17 20:00:00    17.000000
Freq: 4H, Name: DryBulbCelsius, dtype: float64

In [67]:
weather.loc['2014-06-02'].resample('4H').mean()
#weather.resample('4H').mean()['DryBulbCelsius']

#times = pd.DatetimeIndex(weather.index)
#weather.groupby(weather.index.hour).mean()

,WBAN,StationType,Visibility,WindSpeed,WindDirection,StationPressure,Altimeter
Date_Time,,,,,,,
2014-06-02 00:00:00,3011.0,0.0,10.0,5.666667,107.777778,21.593333,30.283333
2014-06-02 04:00:00,3011.0,0.0,10.0,4.636364,95.454545,21.620000,30.316364
2014-06-02 08:00:00,3011.0,0.0,10.0,6.500000,143.333333,21.621667,30.321667
2014-06-02 12:00:00,3011.0,0.0,10.0,8.375000,192.500000,21.597500,30.287500
2014-06-02 16:00:00,3011.0,0.0,10.0,6.636364,151.818182,21.600909,30.290909
2014-06-02 20:00:00,3011.0,0.0,10.0,6.333333,90.000000,21.582222,30.268889

In [58]:
annual_sales = fancy.groupby(lambda x: x.year).sum()

#fancy

In [95]:
return Series(round(annual_sales.mean(), 2), index =['sales'])

sales    171787.05
dtype: float64

In [68]:
dates = pd.DatetimeIndex(start = '01/01/1987', periods = 84, freq = 'M')
fancy = pd.read_csv("fancy.dat", header = None, names = ['sales'], squeeze = True)
fancy.index = dates

In [79]:
fancy.groupby(lambda x: x.month).max().idxmax()

12

In [15]:
pd.DatetimeIndex(start = '01/01/1987', periods = 84, freq = 'M')

DatetimeIndex(['1987-01-31', '1987-02-28', '1987-03-31', '1987-04-30',
               '1987-05-31', '1987-06-30', '1987-07-31', '1987-08-31',
               '1987-09-30', '1987-10-31', '1987-11-30', '1987-12-31',
               '1988-01-31', '1988-02-29', '1988-03-31', '1988-04-30',
               '1988-05-31', '1988-06-30', '1988-07-31', '1988-08-31',
               '1988-09-30', '1988-10-31', '1988-11-30', '1988-12-31',
               '1989-01-31', '1989-02-28', '1989-03-31', '1989-04-30',
               '1989-05-31', '1989-06-30', '1989-07-31', '1989-08-31',
               '1989-09-30', '1989-10-31', '1989-11-30', '1989-12-31',
               '1990-01-31', '1990-02-28', '1990-03-31', '1990-04-30',
               '1990-05-31', '1990-06-30', '1990-07-31', '1990-08-31',
               '1990-09-30', '1990-10-31', '1990-11-30', '1990-12-31',
               '1991-01-31', '1991-02-28', '1991-03-31', '1991-04-30',
               '1991-05-31', '1991-06-30', '1991-07-31', '1991-08-31',
               '1991-09-30', '1991-10-31', '1991-11-30', '1991-12-31',
               '1992-01-31', '1992-02-29', '1992-03-31', '1992-04-30',
               '1992-05-31', '1992-06-30', '1992-07-31', '1992-08-31',
               '1992-09-30', '1992-10-31', '1992-11-30', '1992-12-31',
               '1993-01-31', '1993-02-28', '1993-03-31', '1993-04-30',
               '1993-05-31', '1993-06-30', '1993-07-31', '1993-08-31',
               '1993-09-30', '1993-10-31', '1993-11-30', '1993-12-31'],
              dtype='datetime64[ns]', freq='M')