In [1]:
import pandas as pd
from pandas import Series, DataFrame
import datetime as dt
import numpy as np

In [2]:
cols = ['Date', 'team', 'function', 'valid_error', 'n', 'output', 'time', 'exceptions']

functions_df = pd.read_csv('results.csv', header = None, names = cols)

In [11]:
test_df = functions_df[functions_df['function'] == 'new_nation_n_states']
test_df = test_df[test_df.valid_error == 'valid']

In [15]:
x = DataFrame(test_df.groupby(["n", "team"], as_index = False)['output'].max())

In [27]:
x[x.n == 1][x[x.n == 1].output != max(x[x.n == 1].output)]

      n                               team      output
2   1.0                    Border Horsemen         0.0
9   1.0                    Flying Dutchman    759000.0
11  1.0  Give Me Liberty or Give Me Death!  20039000.0
17  1.0                              OP GG    759000.0
20  1.0            Python, do you love me?    759000.0
30  1.0                     United Misfits    522000.0

In [32]:
test_df.groupby(["team", "n"])['output'].max()

team                 n
A_team               1.0      34888000.0
                     2.0      39325000.0
                     3.0      44362000.0
                     4.0      61187000.0
                     5.0      66805000.0
                     6.0      72263562.0
                     7.0      84431562.0
                     8.0      92253000.0
                     9.0     101929562.0
Back in the US       1.0      34888000.0
                     2.0      39325000.0
                     3.0      43384000.0
                     4.0      46788000.0
                     5.0      52858000.0
                     6.0      56240000.0
                     7.0      76279000.0
                     8.0      81737562.0
                     9.0      93905562.0
                     10.0     99950562.0
                     11.0    111403562.0
                     12.0    123699562.0
                     13.0    141936562.0
                     14.0    151695562.0
                     15.0    159830562.0
                     16.0    165780562.0
                     17.0    171318562.0
                     18.0    178955562.0
                     19.0    194268562.0
                     20.0    201885562.0
                     21.0    208933562.0
                                ...
sunkenstates         21.0    208933562.0
                     22.0    214314562.0
                     23.0    219636562.0
                     24.0    224464562.0
                     25.0    228949562.0
the bug stops here.  1.0      34888000.0
                     2.0      39325000.0
                     3.0      44362000.0
                     4.0      61187000.0
                     5.0      66805000.0
                     6.0      72263562.0
                     7.0      84431562.0
                     8.0      87009562.0
                     9.0      97871000.0
                     10.0    104507562.0
                     11.0    116803562.0
                     12.0    135040562.0
                     13.0    144799562.0
                     14.0    152934562.0
                     15.0    154020562.0
                     16.0    159015562.0
                     17.0    166063562.0
                     18.0    173680562.0
                     19.0    181317562.0
                     20.0    196630562.0
                     21.0    202168562.0
                     22.0    206653562.0
                     23.0    210642562.0
                     24.0    213881562.0
                     25.0    215232562.0
Name: output, Length: 847, dtype: float64

In [13]:
test_df[test_df['team'] == 'Rick and Morty']

,Date,team,function,valid_error,n,output,time,exceptions
2337,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,1.0,34888000.0,0.024021,NaN
2338,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,2.0,34888000.0,0.010414,NaN
2339,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,3.0,34888000.0,0.010299,NaN
2340,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,4.0,34888000.0,0.010104,NaN
2341,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,5.0,34888000.0,0.010364,NaN
2342,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,6.0,34888000.0,0.010476,NaN
2343,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,7.0,34888000.0,0.011143,NaN
2344,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,8.0,34888000.0,0.010604,NaN
2345,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,9.0,34888000.0,0.010697,NaN
2346,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,10.0,34888000.0,0.010996,NaN
2347,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,11.0,34888000.0,0.011082,NaN
2348,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,12.0,34888000.0,0.011698,NaN
2349,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,13.0,34888000.0,0.011748,NaN
2350,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,14.0,34888000.0,0.011675,NaN
2351,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,15.0,34888000.0,0.011978,NaN
2352,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,16.0,34888000.0,0.012599,NaN
2353,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,17.0,34888000.0,0.012509,NaN
2354,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,18.0,34888000.0,0.012967,NaN
2355,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,19.0,34888000.0,0.013433,NaN
2356,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,20.0,34888000.0,0.013669,NaN
2357,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,21.0,34888000.0,0.016281,NaN
2358,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,22.0,34888000.0,0.015788,NaN
2359,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,23.0,34888000.0,0.016050,NaN
2360,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,24.0,34888000.0,0.016488,NaN
2361,2018-08-06 00:05:09,Rick and Morty,new_nation_n_states,valid,25.0,34888000.0,0.016354,NaN

In [8]:
split_dfs = []
for i in range(int(min(test_df.n.values)), int(max(test_df.n.values))+1):
    split_dfs.append(test_df[test_df.n == i].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team'))

In [9]:
start = split_dfs[0][split_dfs[0].output != max(split_dfs[0].output)]
teams = start.team.values
df_list = []
df_list.append(start)

for i in split_dfs:
    condition1 = i.output != max(i.output)
    condition2 = ~i.team.isin(teams)
    df_list.append(i[condition1 & condition2])
    teams = np.append(teams, i[condition1 & condition2].team.values)

In [10]:
pd.concat(df_list[::-1])

,Date,team,function,valid_error,n,output,time,exceptions
3370,2018-08-06 16:30:41,Jatt United,new_nation_n_states,valid,14.0,156306562.0,2.216061,NaN
2454,2018-08-06 03:35:14,Deadpool,new_nation_n_states,valid,8.0,90476562.0,2.303886,NaN
2012,2018-08-05 19:35:11,the bug stops here.,new_nation_n_states,valid,8.0,87009562.0,0.370158,NaN
2726,2018-08-06 10:05:09,Divide and conquer,new_nation_n_states,valid,6.0,71283000.0,0.067956,NaN
3236,2018-08-06 14:45:09,OpaqueRat,new_nation_n_states,valid,6.0,71283000.0,0.451543,NaN
3480,2018-08-06 18:25:34,The Republic of Texas,new_nation_n_states,valid,6.0,70661000.0,4.017634,NaN
3124,2018-08-06 14:15:09,Uptown funk you up,new_nation_n_states,valid,6.0,69724000.0,0.155108,NaN
4457,2018-08-07 11:05:08,H.Y. Brothers,new_nation_n_states,valid,6.0,65925000.0,0.002562,NaN
928,2018-08-05 15:05:24,Mavericks,new_nation_n_states,valid,5.0,65665000.0,1.135585,NaN
583,2018-08-05 15:04:55,Tinker Tailor Soldier Spy,new_nation_n_states,valid,4.0,51745000.0,0.007787,NaN
3262,2018-08-06 15:15:08,hehesb,new_nation_n_states,valid,4.0,51745000.0,0.008804,NaN
3383,2018-08-06 17:02:56,Need for Succeed,new_nation_n_states,valid,4.0,51745000.0,0.009101,NaN
485,2018-08-05 15:04:40,asdfghjkl,new_nation_n_states,valid,4.0,51745000.0,0.009621,NaN
254,2018-08-05 15:01:10,You can have it,new_nation_n_states,valid,3.0,43384000.0,0.001418,NaN
1569,2018-08-05 16:17:59,Back in the US,new_nation_n_states,valid,3.0,43384000.0,0.001425,NaN
2412,2018-08-06 01:30:08,UnitedStates.split(),new_nation_n_states,valid,3.0,43384000.0,0.001509,NaN
752,2018-08-05 15:05:11,Carpe Diem,new_nation_n_states,valid,3.0,43384000.0,0.001589,NaN
1594,2018-08-05 17:20:07,Thebutterflyeffect,new_nation_n_states,valid,3.0,43384000.0,0.002346,NaN
825,2018-08-05 15:05:12,sunkenstates,new_nation_n_states,valid,3.0,43384000.0,0.002884,NaN
280,2018-08-05 15:01:33,The United States of Westeros,new_nation_n_states,valid,3.0,43384000.0,0.002918,NaN
2115,2018-08-05 20:45:10,Game of States,new_nation_n_states,valid,3.0,43384000.0,0.003093,NaN
1971,2018-08-05 19:15:09,CIA Operative #6,new_nation_n_states,valid,3.0,43384000.0,0.011879,NaN
655,2018-08-05 15:05:01,We Were (Data)Framed!,new_nation_n_states,valid,3.0,43384000.0,0.012401,NaN
3048,2018-08-06 14:11:45,State of Mind,new_nation_n_states,valid,3.0,43384000.0,0.017901,NaN
415,2018-08-05 15:03:14,Manifest Destiny,new_nation_n_states,valid,3.0,43384000.0,0.030571,NaN
2338,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,2.0,34888000.0,0.010414,NaN
332,2018-08-05 15:02:13,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,1.0,20039000.0,0.001609,NaN
179,2018-08-05 15:01:08,"Python, do you love me?",new_nation_n_states,valid,1.0,759000.0,0.001389,NaN
899,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,1.0,759000.0,0.001493,NaN
2216,2018-08-05 21:50:08,OP GG,new_nation_n_states,valid,1.0,759000.0,0.001540,NaN
3989,2018-08-07 04:10:07,United Misfits,new_nation_n_states,valid,1.0,522000.0,0.001496,NaN
2038,2018-08-05 20:15:09,Border Horsemen,new_nation_n_states,valid,1.0,0.0,0.003296,NaN

In [36]:
condition1 = split_dfs[1].output != max(split_dfs[1].output)
condition2 = ~split_dfs[1].team.isin(teams)

In [37]:
split_dfs[1][condition1 & condition2]

,Date,team,function,valid_error,n,output,time,exceptions
2338,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,2.0,34888000.0,0.010414,NaN

In [161]:
losers_list = []
for i in range(len(split_dfs)):
    losers_list.append(split_dfs[i][split_dfs[i].output != max(split_dfs[i].output)])

In [162]:
losers_list

[                     Date                               team  \
 332   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 179   2018-08-05 15:01:08            Python, do you love me?
 899   2018-08-05 15:05:19                    Flying Dutchman
 2216  2018-08-05 21:50:08                              OP GG
 3989  2018-08-07 04:10:07                     United Misfits
 2038  2018-08-05 20:15:09                    Border Horsemen

                  function valid_error    n      output      time exceptions
 332   new_nation_n_states       valid  1.0  20039000.0  0.001609        NaN
 179   new_nation_n_states       valid  1.0    759000.0  0.001389        NaN
 899   new_nation_n_states       valid  1.0    759000.0  0.001493        NaN
 2216  new_nation_n_states       valid  1.0    759000.0  0.001540        NaN
 3989  new_nation_n_states       valid  1.0    522000.0  0.001496        NaN
 2038  new_nation_n_states       valid  1.0         0.0  0.003296        NaN  ,
                      Date                               team  \
 2338  2018-08-06 00:05:08                     Rick and Morty
 333   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 180   2018-08-05 15:01:08            Python, do you love me?
 2217  2018-08-05 21:50:08                              OP GG
 900   2018-08-05 15:05:19                    Flying Dutchman
 3990  2018-08-07 04:10:07                     United Misfits
 2039  2018-08-05 20:15:09                    Border Horsemen

                  function valid_error    n      output      time exceptions
 2338  new_nation_n_states       valid  2.0  34888000.0  0.010414        NaN
 333   new_nation_n_states       valid  2.0  24517000.0  0.001573        NaN
 180   new_nation_n_states       valid  2.0  13055000.0  0.001366        NaN
 2217  new_nation_n_states       valid  2.0  13055000.0  0.001467        NaN
 900   new_nation_n_states       valid  2.0  13055000.0  0.001551        NaN
 3990  new_nation_n_states       valid  2.0   4581000.0  0.002458        NaN
 2039  new_nation_n_states       valid  2.0         0.0  0.002691        NaN  ,
                      Date                               team  \
 254   2018-08-05 15:01:10                    You can have it
 1569  2018-08-05 16:17:59                     Back in the US
 2412  2018-08-06 01:30:08               UnitedStates.split()
 752   2018-08-05 15:05:11                         Carpe Diem
 1594  2018-08-05 17:20:07                 Thebutterflyeffect
 825   2018-08-05 15:05:12                       sunkenstates
 280   2018-08-05 15:01:33      The United States of Westeros
 2115  2018-08-05 20:45:10                     Game of States
 1971  2018-08-05 19:15:09                   CIA Operative #6
 655   2018-08-05 15:05:01              We Were (Data)Framed!
 3048  2018-08-06 14:11:45                      State of Mind
 415   2018-08-05 15:03:14                   Manifest Destiny
 2339  2018-08-06 00:05:08                     Rick and Morty
 181   2018-08-05 15:01:08            Python, do you love me?
 2218  2018-08-05 21:50:08                              OP GG
 901   2018-08-05 15:05:19                    Flying Dutchman
 334   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 3991  2018-08-07 04:10:07                     United Misfits

                  function valid_error    n      output      time exceptions
 254   new_nation_n_states       valid  3.0  43384000.0  0.001418        NaN
 1569  new_nation_n_states       valid  3.0  43384000.0  0.001425        NaN
 2412  new_nation_n_states       valid  3.0  43384000.0  0.001509        NaN
 752   new_nation_n_states       valid  3.0  43384000.0  0.001589        NaN
 1594  new_nation_n_states       valid  3.0  43384000.0  0.002346        NaN
 825   new_nation_n_states       valid  3.0  43384000.0  0.002884        NaN
 280   new_nation_n_states       valid  3.0  43384000.0  0.002918        NaN
 2115  new_nation_n_states       valid  3.0  43384000.0  0.003093        NaN
 1971  new_nation_n_states       valid  3.0  43384000.0  0.011879        NaN
 655   new_nation_n_states       valid  3.0  43384000.0  0.012401        NaN
 3048  new_nation_n_states       valid  3.0  43384000.0  0.017901        NaN
 415   new_nation_n_states       valid  3.0  43384000.0  0.030571        NaN
 2339  new_nation_n_states       valid  3.0  34888000.0  0.010299        NaN
 181   new_nation_n_states       valid  3.0  31292000.0  0.001426        NaN
 2218  new_nation_n_states       valid  3.0  31292000.0  0.001434        NaN
 901   new_nation_n_states       valid  3.0  31292000.0  0.002116        NaN
 334   new_nation_n_states       valid  3.0  27899000.0  0.001788        NaN
 3991  new_nation_n_states       valid  3.0   9018000.0  0.004573        NaN  ,
                      Date                               team  \
 583   2018-08-05 15:04:55          Tinker Tailor Soldier Spy
 3262  2018-08-06 15:15:08                             hehesb
 3383  2018-08-06 17:02:56                   Need for Succeed
 485   2018-08-05 15:04:40                          asdfghjkl
 416   2018-08-05 15:03:14                   Manifest Destiny
 1017  2018-08-05 15:07:49               UnitedStates.split()
 1570  2018-08-05 16:17:59                     Back in the US
 255   2018-08-05 15:01:10                    You can have it
 753   2018-08-05 15:05:11                         Carpe Diem
 1595  2018-08-05 17:20:07                 Thebutterflyeffect
 281   2018-08-05 15:01:33      The United States of Westeros
 826   2018-08-05 15:05:12                       sunkenstates
 2116  2018-08-05 20:45:10                     Game of States
 2603  2018-08-06 09:45:08              We Were (Data)Framed!
 1972  2018-08-05 19:15:09                   CIA Operative #6
 3049  2018-08-06 14:11:45                      State of Mind
 3992  2018-08-07 04:10:07                     United Misfits
 182   2018-08-05 15:01:08            Python, do you love me?
 902   2018-08-05 15:05:19                    Flying Dutchman
 2219  2018-08-05 21:50:08                              OP GG
 2340  2018-08-06 00:05:08                     Rick and Morty
 335   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!

                  function valid_error    n      output      time exceptions
 583   new_nation_n_states       valid  4.0  51745000.0  0.007787        NaN
 3262  new_nation_n_states       valid  4.0  51745000.0  0.008804        NaN
 3383  new_nation_n_states       valid  4.0  51745000.0  0.009101        NaN
 485   new_nation_n_states       valid  4.0  51745000.0  0.009621        NaN
 416   new_nation_n_states       valid  4.0  51745000.0  0.051203        NaN
 1017  new_nation_n_states       valid  4.0  50121000.0  0.035351        NaN
 1570  new_nation_n_states       valid  4.0  46788000.0  0.001461        NaN
 255   new_nation_n_states       valid  4.0  46788000.0  0.001533        NaN
 753   new_nation_n_states       valid  4.0  46788000.0  0.001560        NaN
 1595  new_nation_n_states       valid  4.0  46788000.0  0.002361        NaN
 281   new_nation_n_states       valid  4.0  46788000.0  0.002905        NaN
 826   new_nation_n_states       valid  4.0  46788000.0  0.003242        NaN
 2116  new_nation_n_states       valid  4.0  46788000.0  0.003317        NaN
 2603  new_nation_n_states       valid  4.0  46788000.0  0.014626        NaN
 1972  new_nation_n_states       valid  4.0  46788000.0  0.017172        NaN
 3049  new_nation_n_states       valid  4.0  46788000.0  0.022122        NaN
 3992  new_nation_n_states       valid  4.0  43906000.0  0.007696        NaN
 182   new_nation_n_states       valid  4.0  42745000.0  0.001483        NaN
 902   new_nation_n_states       valid  4.0  42745000.0  0.001499        NaN
 2219  new_nation_n_states       valid  4.0  42745000.0  0.001725        NaN
 2340  new_nation_n_states       valid  4.0  34888000.0  0.010104        NaN
 335   new_nation_n_states       valid  4.0  33357562.0  0.002360        NaN  ,
                      Date                               team  \
 3263  2018-08-06 15:15:08                             hehesb
 3384  2018-08-06 17:02:56                   Need for Succeed
 486   2018-08-05 15:04:40                          asdfghjkl
 584   2018-08-05 15:04:55          Tinker Tailor Soldier Spy
 928   2018-08-05 15:05:24                          Mavericks
 417   2018-08-05 15:03:14                   Manifest Destiny
 256   2018-08-05 15:01:10                    You can have it
 754   2018-08-05 15:05:11                         Carpe Diem
 2414  2018-08-06 01:30:08               UnitedStates.split()
 1571  2018-08-05 16:17:59                     Back in the US
 1596  2018-08-05 17:20:07                 Thebutterflyeffect
 827   2018-08-05 15:05:12                       sunkenstates
 282   2018-08-05 15:01:33      The United States of Westeros
 2117  2018-08-05 20:45:10                     Game of States
 2604  2018-08-06 09:45:08              We Were (Data)Framed!
 1973  2018-08-05 19:15:09                   CIA Operative #6
 3050  2018-08-06 14:11:45                      State of Mind
 2220  2018-08-05 21:50:08                              OP GG
 183   2018-08-05 15:01:08            Python, do you love me?
 903   2018-08-05 15:05:19                    Flying Dutchman
 3993  2018-08-07 04:10:07                     United Misfits
 336   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 2341  2018-08-06 00:05:08                     Rick and Morty

                  function valid_error    n      output      time exceptions
 3263  new_nation_n_states       valid  5.0  65665000.0  0.012910        NaN
 3384  new_nation_n_states       valid  5.0  65665000.0  0.013116        NaN
 486   new_nation_n_states       valid  5.0  65665000.0  0.013816        NaN
 584   new_nation_n_states       valid  5.0  65665000.0  0.014658        NaN
 928   new_nation_n_states       valid  5.0  65665000.0  1.135585        NaN
 417   new_nation_n_states       valid  5.0  59880000.0  0.076873        NaN
 256   new_nation_n_states       valid  5.0  52858000.0  0.001554        NaN
 754   new_nation_n_states       valid  5.0  52858000.0  0.001593        NaN
 2414  new_nation_n_states       valid  5.0  52858000.0  0.001595        NaN
 1571  new_nation_n_states       valid  5.0  52858000.0  0.001654        NaN
 1596  new_nation_n_states       valid  5.0  52858000.0  0.002610        NaN
 827   new_nation_n_states       valid  5.0  52858000.0  0.002987        NaN
 282   new_nation_n_states       valid  5.0  52858000.0  0.003272        NaN
 2117  new_nation_n_states       valid  5.0  52858000.0  0.003796        NaN
 2604  new_nation_n_states       valid  5.0  52858000.0  0.016801        NaN
 1973  new_nation_n_states       valid  5.0  52858000.0  0.023592        NaN
 3050  new_nation_n_states       valid  5.0  52858000.0  0.026043        NaN
 2220  new_nation_n_states       valid  5.0  52504000.0  0.001545        NaN
 183   new_nation_n_states       valid  5.0  52504000.0  0.001607        NaN
 903   new_nation_n_states       valid  5.0  52504000.0  0.001747        NaN
 3993  new_nation_n_states       valid  5.0  47310000.0  0.011204        NaN
 336   new_nation_n_states       valid  5.0  43153000.0  0.003007        NaN
 2341  new_nation_n_states       valid  5.0  34888000.0  0.010364        NaN  ,
                      Date                               team  \
 2726  2018-08-06 10:05:09                 Divide and conquer
 3236  2018-08-06 14:45:09                          OpaqueRat
 4397  2018-08-07 10:51:10                          Mavericks
 3480  2018-08-06 18:25:34              The Republic of Texas
 585   2018-08-05 15:04:55          Tinker Tailor Soldier Spy
 3337  2018-08-06 15:50:35                             hehesb
 3385  2018-08-06 17:02:56                   Need for Succeed
 487   2018-08-05 15:04:40                          asdfghjkl
 418   2018-08-05 15:03:14                   Manifest Destiny
 3124  2018-08-06 14:15:09                 Uptown funk you up
 4457  2018-08-07 11:05:08                      H.Y. Brothers
 2221  2018-08-05 21:50:08                              OP GG
 184   2018-08-05 15:01:08            Python, do you love me?
 904   2018-08-05 15:05:19                    Flying Dutchman
 1572  2018-08-05 16:17:59                     Back in the US
 755   2018-08-05 15:05:11                         Carpe Diem
 257   2018-08-05 15:01:10                    You can have it
 2415  2018-08-06 01:30:08               UnitedStates.split()
 1597  2018-08-05 17:20:07                 Thebutterflyeffect
 828   2018-08-05 15:05:12                       sunkenstates
 283   2018-08-05 15:01:33      The United States of Westeros
 2118  2018-08-05 20:45:10                     Game of States
 658   2018-08-05 15:05:01              We Were (Data)Framed!
 3051  2018-08-06 14:11:46                      State of Mind
 1974  2018-08-05 19:15:09                   CIA Operative #6
 3994  2018-08-07 04:10:07                     United Misfits
 337   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 2342  2018-08-06 00:05:08                     Rick and Morty

                  function valid_error    n      output      time exceptions
 2726  new_nation_n_states       valid  6.0  71283000.0  0.067956        NaN
 3236  new_nation_n_states       valid  6.0  71283000.0  0.451543        NaN
 4397  new_nation_n_states       valid  6.0  71283000.0  1.679231        NaN
 3480  new_nation_n_states       valid  6.0  70661000.0  4.017634        NaN
 585   new_nation_n_states       valid  6.0  69958000.0  0.016893        NaN
 3337  new_nation_n_states       valid  6.0  69958000.0  0.018023        NaN
 3385  new_nation_n_states       valid  6.0  69958000.0  0.018162        NaN
 487   new_nation_n_states       valid  6.0  69958000.0  0.018650        NaN
 418   new_nation_n_states       valid  6.0  69958000.0  0.107942        NaN
 3124  new_nation_n_states       valid  6.0  69724000.0  0.155108        NaN
 4457  new_nation_n_states       valid  6.0  65925000.0  0.002562        NaN
 2221  new_nation_n_states       valid  6.0  60639000.0  0.001631        NaN
 184   new_nation_n_states       valid  6.0  60639000.0  0.001666        NaN
 904   new_nation_n_states       valid  6.0  60639000.0  0.002076        NaN
 1572  new_nation_n_states       valid  6.0  56240000.0  0.001655        NaN
 755   new_nation_n_states       valid  6.0  56240000.0  0.001706        NaN
 257   new_nation_n_states       valid  6.0  56240000.0  0.001715        NaN
 2415  new_nation_n_states       valid  6.0  56240000.0  0.001751        NaN
 1597  new_nation_n_states       valid  6.0  56240000.0  0.002956        NaN
 828   new_nation_n_states       valid  6.0  56240000.0  0.003033        NaN
 283   new_nation_n_states       valid  6.0  56240000.0  0.003038        NaN
 2118  new_nation_n_states       valid  6.0  56240000.0  0.004407        NaN
 658   new_nation_n_states       valid  6.0  56240000.0  0.019324        NaN
 3051  new_nation_n_states       valid  6.0  56240000.0  0.030336        NaN
 1974  new_nation_n_states       valid  6.0  56240000.0  0.031709        NaN
 3994  new_nation_n_states       valid  6.0  53380000.0  0.016377        NaN
 337   new_nation_n_states       valid  6.0  48611562.0  0.003354        NaN
 2342  new_nation_n_states       valid  6.0  34888000.0  0.010476        NaN  ,
                      Date                               team  \
 2727  2018-08-06 10:05:09                 Divide and conquer
 930   2018-08-05 15:05:27                          Mavericks
 3237  2018-08-06 14:45:11                          OpaqueRat
 4458  2018-08-07 11:05:08                      H.Y. Brothers
 2526  2018-08-06 08:15:09              The Republic of Texas
 3265  2018-08-06 15:15:08                             hehesb
 586   2018-08-05 15:04:55          Tinker Tailor Soldier Spy
 3386  2018-08-06 17:02:56                   Need for Succeed
 488   2018-08-05 15:04:40                          asdfghjkl
 419   2018-08-05 15:03:14                   Manifest Destiny
 756   2018-08-05 15:05:11                         Carpe Diem
 258   2018-08-05 15:01:10                    You can have it
 1573  2018-08-05 16:17:59                     Back in the US
 2416  2018-08-06 01:30:09               UnitedStates.split()
 1598  2018-08-05 17:20:07                 Thebutterflyeffect
 284   2018-08-05 15:01:33      The United States of Westeros
 829   2018-08-05 15:05:12                       sunkenstates
 2119  2018-08-05 20:45:10                     Game of States
 2606  2018-08-06 09:45:08              We Were (Data)Framed!
 3052  2018-08-06 14:11:46                      State of Mind
 1975  2018-08-05 19:15:09                   CIA Operative #6
 3125  2018-08-06 14:15:10                 Uptown funk you up
 185   2018-08-05 15:01:09            Python, do you love me?
 2222  2018-08-05 21:50:08                              OP GG
 905   2018-08-05 15:05:19                    Flying Dutchman
 338   2018-08-05 15:02:13  Give Me Liberty or Give Me Death!
 3995  2018-08-07 04:10:07                     United Misfits
 2343  2018-08-06 00:05:08                     Rick and Morty
 109   2018-08-05 15:00:48                           SwatKats
 321   2018-08-05 15:02:03                         ChickenRun
 1997  2018-08-05 19:25:14                              Pyxit

                  function valid_error    n      output      time  \
 2727  new_nation_n_states       valid  7.0  82195562.0  0.083035
 930   new_nation_n_states       valid  7.0  82195562.0  1.775328
 3237  new_nation_n_states       valid  7.0  82195562.0  2.210340
 4458  new_nation_n_states       valid  7.0  78093000.0  0.003090
 2526  new_nation_n_states       valid  7.0  78093000.0  0.022303
 3265  new_nation_n_states       valid  7.0  78093000.0  0.023747
 586   new_nation_n_states       valid  7.0  78093000.0  0.023990
 3386  new_nation_n_states       valid  7.0  78093000.0  0.024340
 488   new_nation_n_states       valid  7.0  78093000.0  0.025903
 419   new_nation_n_states       valid  7.0  78093000.0  0.145248
 756   new_nation_n_states       valid  7.0  76279000.0  0.001815
 258   new_nation_n_states       valid  7.0  76279000.0  0.001817
 1573  new_nation_n_states       valid  7.0  76279000.0  0.001830
 2416  new_nation_n_states       valid  7.0  76279000.0  0.001836
 1598  new_nation_n_states       valid  7.0  76279000.0  0.002926
 284   new_nation_n_states       valid  7.0  76279000.0  0.003319
 829   new_nation_n_states       valid  7.0  76279000.0  0.003346
 2119  new_nation_n_states       valid  7.0  76279000.0  0.005222
 2606  new_nation_n_states       valid  7.0  76279000.0  0.021962
 3052  new_nation_n_states       valid  7.0  76279000.0  0.034968
 1975  new_nation_n_states       valid  7.0  76279000.0  0.041310
 3125  new_nation_n_states       valid  7.0  72474000.0  0.236494
 185   new_nation_n_states       valid  7.0  66684000.0  0.001736
 2222  new_nation_n_states       valid  7.0  66684000.0  0.001828
 905   new_nation_n_states       valid  7.0  66684000.0  0.002204
 338   new_nation_n_states       valid  7.0  60779562.0  0.004125
 3995  new_nation_n_states       valid  7.0  56762000.0  0.022246
 2343  new_nation_n_states       valid  7.0  34888000.0  0.011143
 109   new_nation_n_states     timeout  7.0         NaN       NaN
 321   new_nation_n_states     timeout  7.0         NaN       NaN
 1997  new_nation_n_states     timeout  7.0         NaN       NaN

                                              exceptions
 2727                                                NaN
 930                                                 NaN
 3237                                                NaN
 4458                                                NaN
 2526                                                NaN
 3265                                                NaN
 586                                                 NaN
 3386                                                NaN

In [151]:
new_df = split_dfs[1][~split_dfs[1].team.isin(losers_list[0].team)]

In [144]:
losers_list.append(new_df[0][split_dfs[0].output != max(split_dfs[0].output)])
losers_list

,Date,team,function,valid_error,n,output,time,exceptions
332,2018-08-05 15:02:13,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,1.0,20039000.0,0.001609,NaN
179,2018-08-05 15:01:08,"Python, do you love me?",new_nation_n_states,valid,1.0,759000.0,0.001389,NaN
899,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,1.0,759000.0,0.001493,NaN
2216,2018-08-05 21:50:08,OP GG,new_nation_n_states,valid,1.0,759000.0,0.001540,NaN
3989,2018-08-07 04:10:07,United Misfits,new_nation_n_states,valid,1.0,522000.0,0.001496,NaN
2038,2018-08-05 20:15:09,Border Horsemen,new_nation_n_states,valid,1.0,0.0,0.003296,NaN

In [158]:
split_dfs[1][~split_dfs[1].team.isin(losers_list[0].team)].output != max(split_dfs[1][~split_dfs[1].team.isin(losers_list[0].team)].output)

2591    False
2043    False
253     False
751     False
1568    False
4298    False
2411    False
3864    False
3193    False
94      False
1593    False
508     False
2114    False
581     False
824     False
279     False
3381    False
483     False
3120    False
316     False
1999    False
358     False
1292    False
1970    False
654     False
104     False
1726    False
3929    False
3047    False
2448    False
414     False
3232    False
2722    False
925     False
2338     True
Name: output, dtype: bool

In [129]:
empty_list = []
for i in split_dfs:
    empty_list.append((i[i.output == max(i.output)].team.values, max(i.n)))

In [130]:
empty_list

[(array(['What If Analytics', 'A_team', 'Uptown funk you up', 'Cession',
         'You can have it', 'Carpe Diem', 'Tinker Tailor Soldier Spy',
         'UnitedStates.split()', 'Speed Fiends', 'H.Y. Brothers',
         'Back in the US', 'hehesb', 'The Republic of Texas', 'Jatt United',
         'Game of States', 'sunkenstates', 'The United States of Westeros',
         'asdfghjkl', 'Need for Succeed', 'Divide and conquer',
         'Thebutterflyeffect', 'Manifest Destiny', 'We Were (Data)Framed!',
         'CIA Operative #6', 'ChickenRun', 'the bug stops here.',
         'State of Mind', 'SwatKats', 'random2', 'Deadpool', 'Pyxit',
         'PH 10.0', 'Rick and Morty', 'OpaqueRat', 'Mavericks'],
        dtype=object), 1.0),
 (array(['A_team', 'What If Analytics', 'You can have it', 'Carpe Diem',
         'Back in the US', 'H.Y. Brothers', 'UnitedStates.split()',
         'Speed Fiends', 'hehesb', 'Jatt United', 'Thebutterflyeffect',
         'The Republic of Texas', 'Game of States',
         'Tinker Tailor Soldier Spy', 'sunkenstates',
         'The United States of Westeros', 'Need for Succeed', 'asdfghjkl',
         'Uptown funk you up', 'ChickenRun', 'Pyxit', 'the bug stops here.',
         'Cession', 'CIA Operative #6', 'We Were (Data)Framed!', 'SwatKats',
         'random2', 'PH 10.0', 'State of Mind', 'Deadpool',
         'Manifest Destiny', 'OpaqueRat', 'Divide and conquer', 'Mavericks'],
        dtype=object), 2.0),
 (array(['A_team', 'What If Analytics', 'Speed Fiends',
         'Tinker Tailor Soldier Spy', 'The Republic of Texas', 'hehesb',
         'Need for Succeed', 'asdfghjkl', 'the bug stops here.', 'Pyxit',
         'ChickenRun', 'random2', 'Cession', 'Uptown funk you up',
         'PH 10.0', 'H.Y. Brothers', 'Divide and conquer', 'SwatKats',
         'OpaqueRat', 'Deadpool', 'Jatt United', 'Mavericks'], dtype=object),
  3.0),
 (array(['A_team', 'Speed Fiends', 'What If Analytics',
         'the bug stops here.', 'random2', 'Cession', 'Pyxit', 'ChickenRun',
         'PH 10.0', 'Divide and conquer', 'Uptown funk you up', 'OpaqueRat',
         'SwatKats', 'Deadpool', 'H.Y. Brothers', 'Jatt United',
         'Mavericks', 'The Republic of Texas'], dtype=object), 4.0),
 (array(['the bug stops here.', 'random2', 'Cession', 'A_team',
         'Speed Fiends', 'What If Analytics', 'PH 10.0',
         'Divide and conquer', 'Uptown funk you up', 'Pyxit', 'ChickenRun',
         'OpaqueRat', 'Jatt United', 'SwatKats', 'Deadpool',
         'H.Y. Brothers', 'The Republic of Texas'], dtype=object), 5.0),
 (array(['random2', 'Cession', 'the bug stops here.', 'A_team', 'PH 10.0',
         'What If Analytics', 'Speed Fiends', 'Jatt United', 'Pyxit',
         'Deadpool', 'ChickenRun', 'SwatKats'], dtype=object), 6.0),
 (array(['random2', 'Cession', 'PH 10.0', 'A_team', 'the bug stops here.',
         'What If Analytics', 'Jatt United', 'Deadpool', 'Speed Fiends'],
        dtype=object), 7.0),
 (array(['random2', 'Divide and conquer', 'Cession', 'PH 10.0',
         'Jatt United', 'A_team', 'What If Analytics', 'Mavericks'],
        dtype=object), 8.0),
 (array(['random2', 'Cession', 'Jatt United', 'PH 10.0', 'Deadpool',
         'A_team'], dtype=object), 9.0),
 (array(['random2', 'Jatt United', 'PH 10.0', 'Deadpool', 'Cession'],
        dtype=object), 10.0),
 (array(['random2', 'Jatt United', 'Deadpool', 'PH 10.0'], dtype=object),
  11.0),
 (array(['random2', 'Jatt United', 'Deadpool'], dtype=object), 12.0),
 (array(['random2', 'Jatt United'], dtype=object), 13.0),
 (array(['random2'], dtype=object), 14.0),
 (array(['random2'], dtype=object), 15.0),
 (array(['random2', 'Jatt United'], dtype=object), 16.0),
 (array(['random2', 'Jatt United'], dtype=object), 17.0),
 (array(['random2', 'Jatt United'], dtype=object), 18.0),
 (array(['random2', 'Jatt United'], dtype=object), 19.0),
 (array(['random2', 'Jatt United'], dtype=object), 20.0),
 (array(['random2', 'Jatt United'], dtype=object), 21.0),
 (array(['random2', 'Jatt United'], dtype=object), 22.0),
 (array(['You can have it', 'hehesb', 'Back in the US', 'H.Y. Brothers',
         'UnitedStates.split()', 'Carpe Diem', 'The Republic of Texas',
         'Thebutterflyeffect', 'The United States of Westeros',
         'sunkenstates', 'Deadpool', 'Game of States',
         'We Were (Data)Framed!', 'random2', 'Need for Succeed',
         'Tinker Tailor Soldier Spy', 'asdfghjkl', 'Manifest Destiny'],
        dtype=object), 23.0),
 (array(['Back in the US', 'You can have it', 'H.Y. Brothers',
         'UnitedStates.split()', 'Carpe Diem', 'The Republic of Texas',
         'Thebutterflyeffect', 'The United States of Westeros', 'hehesb',
         'sunkenstates', 'Deadpool', 'Game of States',
         'We Were (Data)Framed!', 'random2', 'Tinker Tailor Soldier Spy',
         'asdfghjkl', 'Need for Succeed', 'Manifest Destiny'], dtype=object),
  24.0),
 (array(['You can have it', 'hehesb', 'Back in the US', 'Carpe Diem',
         'UnitedStates.split()', 'H.Y. Brothers', 'Thebutterflyeffect',
         'The Republic of Texas', 'The United States of Westeros',
         'sunkenstates', 'Deadpool', 'Game of States',
         'We Were (Data)Framed!', 'random2', 'Need for Succeed',
         'Tinker Tailor Soldier Spy', 'asdfghjkl', 'Manifest Destiny'],
        dtype=object), 25.0)]

In [4]:
test_df.head(1)

,Date,team,function,valid_error,n,output,time,exceptions
1,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,1.0,34888000.0,0.022014,NaN

In [47]:
winner = []
list_of_dfs = []

while len(winner) 
test_df[test_df['n'] == 1.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [54]:
three_levels = test_df[(test_df.n == 1.0) | (test_df.n == 2.0) | (test_df.n == 3)]

In [74]:
winner = []
list_of_dfs = []
split_dfs = []

for i in range(int(min(three_levels.n.values)), int(max(three_levels.n.values))+1):
    split_dfs.append(three_levels[three_levels.n == i].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team'))


#three_levels[three_levels.n == 1].sort_values(by = ['output', 'time'], 
 #                                               ascending = [False, True]).drop_duplicates('team')

In [91]:
for i in split_dfs:
    print(i[i.output == max(i.output)].team.values)

['What If Analytics' 'A_team' 'Uptown funk you up' 'Cession'
 'You can have it' 'Carpe Diem' 'Tinker Tailor Soldier Spy'
 'UnitedStates.split()' 'Speed Fiends' 'H.Y. Brothers' 'Back in the US'
 'hehesb' 'The Republic of Texas' 'Jatt United' 'Game of States'
 'sunkenstates' 'The United States of Westeros' 'asdfghjkl'
 'Need for Succeed' 'Divide and conquer' 'Thebutterflyeffect'
 'Manifest Destiny' 'We Were (Data)Framed!' 'CIA Operative #6'
 'ChickenRun' 'the bug stops here.' 'State of Mind' 'SwatKats' 'random2'
 'Deadpool' 'Pyxit' 'PH 10.0' 'Rick and Morty' 'OpaqueRat' 'Mavericks']
['A_team' 'What If Analytics' 'You can have it' 'Carpe Diem'
 'Back in the US' 'H.Y. Brothers' 'UnitedStates.split()' 'Speed Fiends'
 'hehesb' 'Jatt United' 'Thebutterflyeffect' 'The Republic of Texas'
 'Game of States' 'Tinker Tailor Soldier Spy' 'sunkenstates'
 'The United States of Westeros' 'Need for Succeed' 'asdfghjkl'
 'Uptown funk you up' 'ChickenRun' 'Pyxit' 'the bug stops here.' 'Cession'
 'CIA Operative #6' 'We Were (Data)Framed!' 'SwatKats' 'random2' 'PH 10.0'
 'State of Mind' 'Deadpool' 'Manifest Destiny' 'OpaqueRat'
 'Divide and conquer' 'Mavericks']
['A_team' 'What If Analytics' 'Speed Fiends' 'Tinker Tailor Soldier Spy'
 'The Republic of Texas' 'hehesb' 'Need for Succeed' 'asdfghjkl'
 'the bug stops here.' 'Pyxit' 'ChickenRun' 'random2' 'Cession'
 'Uptown funk you up' 'PH 10.0' 'H.Y. Brothers' 'Divide and conquer'
 'SwatKats' 'OpaqueRat' 'Deadpool' 'Jatt United' 'Mavericks']

In [5]:
test_df[test_df['n'] == 2.0]

,Date,team,function,valid_error,n,output,time,exceptions
2,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,2.0,39325000.0,0.080588,NaN
94,2018-08-05 15:00:23,Jatt United,new_nation_n_states,valid,2.0,39325000.0,0.001713,NaN
104,2018-08-05 15:00:40,SwatKats,new_nation_n_states,valid,2.0,39325000.0,0.010897,NaN
123,2018-08-05 15:00:58,What If Analytics,new_nation_n_states,valid,2.0,39325000.0,0.000978,NaN
180,2018-08-05 15:01:08,"Python, do you love me?",new_nation_n_states,valid,2.0,13055000.0,0.001366,NaN
253,2018-08-05 15:01:10,You can have it,new_nation_n_states,valid,2.0,39325000.0,0.001387,NaN
279,2018-08-05 15:01:33,The United States of Westeros,new_nation_n_states,valid,2.0,39325000.0,0.002873,NaN
316,2018-08-05 15:01:57,ChickenRun,new_nation_n_states,valid,2.0,39325000.0,0.006497,NaN
333,2018-08-05 15:02:13,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,2.0,24517000.0,0.001573,NaN
358,2018-08-05 15:02:16,the bug stops here.,new_nation_n_states,valid,2.0,39325000.0,0.007698,NaN
414,2018-08-05 15:03:14,Manifest Destiny,new_nation_n_states,valid,2.0,39325000.0,0.015909,NaN
483,2018-08-05 15:04:40,asdfghjkl,new_nation_n_states,valid,2.0,39325000.0,0.004586,NaN
508,2018-08-05 15:04:44,The Republic of Texas,new_nation_n_states,valid,2.0,39325000.0,0.002391,NaN
581,2018-08-05 15:04:55,Tinker Tailor Soldier Spy,new_nation_n_states,valid,2.0,39325000.0,0.002801,NaN
654,2018-08-05 15:05:01,We Were (Data)Framed!,new_nation_n_states,valid,2.0,39325000.0,0.009725,NaN
681,2018-08-05 15:05:07,CIA Operative #6,new_nation_n_states,valid,2.0,39325000.0,0.008882,NaN
751,2018-08-05 15:05:11,Carpe Diem,new_nation_n_states,valid,2.0,39325000.0,0.001392,NaN
824,2018-08-05 15:05:12,sunkenstates,new_nation_n_states,valid,2.0,39325000.0,0.002816,NaN
900,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,2.0,13055000.0,0.001551,NaN
925,2018-08-05 15:05:22,Mavericks,new_nation_n_states,valid,2.0,39325000.0,0.360731,NaN
1015,2018-08-05 15:07:49,UnitedStates.split(),new_nation_n_states,valid,2.0,39325000.0,0.029571,NaN
1292,2018-08-05 16:17:20,Cession,new_nation_n_states,valid,2.0,39325000.0,0.008113,NaN
1447,2018-08-05 16:17:48,OpaqueRat,new_nation_n_states,valid,2.0,13055000.0,0.001412,NaN
1568,2018-08-05 16:17:59,Back in the US,new_nation_n_states,valid,2.0,39325000.0,0.001412,NaN
1593,2018-08-05 17:20:07,Thebutterflyeffect,new_nation_n_states,valid,2.0,39325000.0,0.002380,NaN
1726,2018-08-05 18:45:32,random2,new_nation_n_states,valid,2.0,39325000.0,0.011858,NaN
1751,2018-08-05 18:55:08,random2,new_nation_n_states,valid,2.0,39325000.0,0.011955,NaN
1824,2018-08-05 19:00:08,Deadpool,new_nation_n_states,valid,2.0,39325000.0,0.015344,NaN
1961,2018-08-05 19:10:38,PH 10.0,new_nation_n_states,valid,2.0,39325000.0,0.017763,NaN
1970,2018-08-05 19:15:09,CIA Operative #6,new_nation_n_states,valid,2.0,39325000.0,0.008597,NaN
...,...,...,...,...,...,...,...,...
2846,2018-08-06 13:20:08,Jatt United,new_nation_n_states,valid,2.0,39325000.0,0.002083,NaN
2906,2018-08-06 13:35:08,Speed Fiends,new_nation_n_states,valid,2.0,39325000.0,0.020554,NaN
3047,2018-08-06 14:11:45,State of Mind,new_nation_n_states,valid,2.0,39325000.0,0.013883,NaN
3120,2018-08-06 14:15:09,Uptown funk you up,new_nation_n_states,valid,2.0,39325000.0,0.006100,NaN
3193,2018-08-06 14:25:09,hehesb,new_nation_n_states,valid,2.0,39325000.0,0.001658,NaN
3218,2018-08-06 14:35:07,Jatt United,new_nation_n_states,valid,2.0,39325000.0,0.001890,NaN
3232,2018-08-06 14:45:08,OpaqueRat,new_nation_n_states,valid,2.0,39325000.0,0.020867,NaN
3240,2018-08-06 14:55:08,Jatt United,new_nation_n_states,valid,2.0,39325000.0,0.001985,NaN
3260,2018-08-06 15:15:08,hehesb,new_nation_n_states,valid,2.0,39325000.0,0.003742,NaN
3333,2018-08-06 15:50:35,hehesb,new_nation_n_states,valid,2.0,39325000.0,0.008727,NaN
3358,2018-08-06 16:30:28,Jatt United,new_nation_n_states,valid,2.0,39325000.0,0.001819,NaN
3381,2018-08-06 17:02:56,Need for Succeed,new_nation_n_states,valid,2.0,39325000.0,0.004275,NaN
3450,2018-08-06 17:45:09,Deadpool,new_nation_n_states,valid,2.0,39325000.0,0.015456,NaN
3464,2018-08-06 17:55:25,Deadpool,new_nation_n_states,valid,2.0,39325000.0,0.016429,NaN
3476,2018-08-06 18:25:18,The Republic of Texas,new_nation_n_states,valid,2.0,39325000.0,4.004637,NaN
3501,2018-08-06 18:30:39,random2,new_nation_n_states,valid,2.0,39325000.0,0.012646,NaN
3574,2018-08-06 18:40:19,The Republic of Texas,new_nation_n_states,valid,2.0,39325000.0,4.204602,NaN
3647,2018-08-06 18:45:48,random2,new_nation_n_states,valid,2.0,39325000.0,0.018958,NaN
3672,2018-08-06 19:05:51,random2,new_nation_n_states,valid,2.0,39325000.0,0.012421,NaN
3864,2018-08-07 01:40:08,Speed Fiends,new_nation_n_states,valid,2.0,39325000.0,0.001618,NaN
3929,2018-08-07 02:45:09,PH 10.0,new_nation_n_states,valid,2.0,39325000.0,0.012550,NaN
3990,2018-08-07 04:10:07,United Misfits,new_nation_n_states,valid,2.0,4581000.0,0.002458,NaN
4064,2018-08-07 07:55:08,H.Y. Brothers,new_nation_n_states,valid,2.0,13055000.0,0.001458,NaN
4146,2018-08-07 08:10:13,H.Y. Brothers,new_nation_n_states,valid,2.0,39325000.0,0.004112,NaN
4152,2018-08-07 09:20:16,The Republic of Texas,new_nation_n_states,valid,2.0,39325000.0,4.304405,NaN
4225,2018-08-07 09:30:09,H.Y. Brothers,new_nation_n_states,valid,2.0,13055000.0,0.002003,NaN
4298,2018-08-07 10:10:09,H.Y. Brothers,new_nation_n_states,valid,2.0,39325000.0,0.001490,NaN
4393,2018-08-07 10:51:06,Mavericks,new_nation_n_states,valid,2.0,39325000.0,0.406305,NaN
4453,2018-08-07 11:05:08,H.Y. Brothers,new_nation_n_states,valid,2.0,30533000.0,0.001520,NaN
4526,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,2.0,39325000.0,0.001829,NaN

In [6]:
list_of_dfs = []

In [9]:
x_df = test_df[test_df['n'] == 1.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [11]:
losers = x_df[x_df['output'] != max(x_df['output'])]
list_of_dfs.append(losers)

In [20]:
losing_teams = losers.team.values

In [27]:
second_df = test_df[test_df['n'] == 2.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [32]:
second_df = second_df[~second_df['team'].isin(losing_teams)]

In [37]:
loser_after2 = second_df[second_df['output'] != max(second_df['output'])]

In [38]:
list_of_dfs.append(loser_after2)

In [41]:
reverse = list_of_dfs[::-1]

In [46]:
pd.concat(reverse)

,Date,team,function,valid_error,n,output,time,exceptions
2338,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,2.0,34888000.0,0.010414,NaN
332,2018-08-05 15:02:13,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,1.0,20039000.0,0.001609,NaN
179,2018-08-05 15:01:08,"Python, do you love me?",new_nation_n_states,valid,1.0,759000.0,0.001389,NaN
899,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,1.0,759000.0,0.001493,NaN
2216,2018-08-05 21:50:08,OP GG,new_nation_n_states,valid,1.0,759000.0,0.001540,NaN
3989,2018-08-07 04:10:07,United Misfits,new_nation_n_states,valid,1.0,522000.0,0.001496,NaN
2038,2018-08-05 20:15:09,Border Horsemen,new_nation_n_states,valid,1.0,0.0,0.003296,NaN

In [114]:
losers_after_round1 = test_df[test_df['n'] == 1.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [131]:


sorted_df = test_df[test_df['n'] == 1.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [134]:
winners = sorted_df[sorted_df['output'] == max(sorted_df['output'])]['team']

In [141]:
losers = sorted_df[sorted_df['output'] != max(sorted_df['output'])]

In [142]:
losers

,Date,team,function,valid_error,n,output,time,exceptions
332,2018-08-05 15:02:13,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,1.0,20039000.0,0.001609,NaN
179,2018-08-05 15:01:08,"Python, do you love me?",new_nation_n_states,valid,1.0,759000.0,0.001389,NaN
899,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,1.0,759000.0,0.001493,NaN
2216,2018-08-05 21:50:08,OP GG,new_nation_n_states,valid,1.0,759000.0,0.001540,NaN
3989,2018-08-07 04:10:07,United Misfits,new_nation_n_states,valid,1.0,522000.0,0.001496,NaN
2038,2018-08-05 20:15:09,Border Horsemen,new_nation_n_states,valid,1.0,0.0,0.003296,NaN

In [144]:
level2 = test_df[test_df['n'] == 2.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [149]:
level2 = level2[level2.team.isin(winners)]

In [159]:
losers = losers.append(level2[level2['output'] != max(level2['output'])])

In [160]:
winners = level2[level2['output'] == max(level2['output'])]['team']

In [162]:
level3 = test_df[test_df['n'] == 3.0].sort_values(by = ['output', 'time'], 
                                                ascending = [False, True]).drop_duplicates('team')

In [168]:
level3[~level3.team.isin(losers.team)]

,Date,team,function,valid_error,n,output,time,exceptions
2592,2018-08-06 09:44:52,A_team,new_nation_n_states,valid,3.0,44362000.0,0.001432,NaN
2044,2018-08-05 20:40:08,What If Analytics,new_nation_n_states,valid,3.0,44362000.0,0.002057,NaN
3865,2018-08-07 01:40:08,Speed Fiends,new_nation_n_states,valid,3.0,44362000.0,0.002366,NaN
582,2018-08-05 15:04:55,Tinker Tailor Soldier Spy,new_nation_n_states,valid,3.0,44362000.0,0.004585,NaN
2522,2018-08-06 08:15:09,The Republic of Texas,new_nation_n_states,valid,3.0,44362000.0,0.004889,NaN
3261,2018-08-06 15:15:08,hehesb,new_nation_n_states,valid,3.0,44362000.0,0.005712,NaN
3382,2018-08-06 17:02:56,Need for Succeed,new_nation_n_states,valid,3.0,44362000.0,0.006347,NaN
484,2018-08-05 15:04:40,asdfghjkl,new_nation_n_states,valid,3.0,44362000.0,0.007471,NaN
359,2018-08-05 15:02:16,the bug stops here.,new_nation_n_states,valid,3.0,44362000.0,0.008113,NaN
2000,2018-08-05 19:30:08,Pyxit,new_nation_n_states,valid,3.0,44362000.0,0.010127,NaN
317,2018-08-05 15:01:57,ChickenRun,new_nation_n_states,valid,3.0,44362000.0,0.011500,NaN
1727,2018-08-05 18:45:32,random2,new_nation_n_states,valid,3.0,44362000.0,0.012215,NaN
1293,2018-08-05 16:17:20,Cession,new_nation_n_states,valid,3.0,44362000.0,0.014864,NaN
3121,2018-08-06 14:15:09,Uptown funk you up,new_nation_n_states,valid,3.0,44362000.0,0.015756,NaN
3930,2018-08-07 02:45:09,PH 10.0,new_nation_n_states,valid,3.0,44362000.0,0.017929,NaN
4147,2018-08-07 08:10:13,H.Y. Brothers,new_nation_n_states,valid,3.0,44362000.0,0.018301,NaN
3,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,3.0,44362000.0,0.029478,NaN
105,2018-08-05 15:00:40,SwatKats,new_nation_n_states,valid,3.0,44362000.0,0.030339,NaN
3233,2018-08-06 14:45:08,OpaqueRat,new_nation_n_states,valid,3.0,44362000.0,0.033474,NaN
2449,2018-08-06 03:35:09,Deadpool,new_nation_n_states,valid,3.0,44362000.0,0.037729,NaN
3219,2018-08-06 14:35:08,Jatt United,new_nation_n_states,valid,3.0,44362000.0,0.053775,NaN
926,2018-08-05 15:05:22,Mavericks,new_nation_n_states,valid,3.0,44362000.0,0.594220,NaN
254,2018-08-05 15:01:10,You can have it,new_nation_n_states,valid,3.0,43384000.0,0.001418,NaN
1569,2018-08-05 16:17:59,Back in the US,new_nation_n_states,valid,3.0,43384000.0,0.001425,NaN
2412,2018-08-06 01:30:08,UnitedStates.split(),new_nation_n_states,valid,3.0,43384000.0,0.001509,NaN
752,2018-08-05 15:05:11,Carpe Diem,new_nation_n_states,valid,3.0,43384000.0,0.001589,NaN
1594,2018-08-05 17:20:07,Thebutterflyeffect,new_nation_n_states,valid,3.0,43384000.0,0.002346,NaN
825,2018-08-05 15:05:12,sunkenstates,new_nation_n_states,valid,3.0,43384000.0,0.002884,NaN
280,2018-08-05 15:01:33,The United States of Westeros,new_nation_n_states,valid,3.0,43384000.0,0.002918,NaN
2115,2018-08-05 20:45:10,Game of States,new_nation_n_states,valid,3.0,43384000.0,0.003093,NaN
1971,2018-08-05 19:15:09,CIA Operative #6,new_nation_n_states,valid,3.0,43384000.0,0.011879,NaN
655,2018-08-05 15:05:01,We Were (Data)Framed!,new_nation_n_states,valid,3.0,43384000.0,0.012401,NaN
3048,2018-08-06 14:11:45,State of Mind,new_nation_n_states,valid,3.0,43384000.0,0.017901,NaN
415,2018-08-05 15:03:14,Manifest Destiny,new_nation_n_states,valid,3.0,43384000.0,0.030571,NaN

In [103]:
test_df.groupby(['team','n', 'time'])['output'].max()

team                 n     time
A_team               1.0   0.000115     34888000.0
                     2.0   0.000462     39325000.0
                     3.0   0.001432     44362000.0
                     4.0   0.004881     61187000.0
                     5.0   0.017265     66805000.0
                     6.0   0.066489     72263562.0
                     7.0   0.256599     84431562.0
                     8.0   0.937998     92253000.0
                     9.0   3.488890    101929562.0
Back in the US       1.0   0.001562     34888000.0
                     2.0   0.001412     39325000.0
                     3.0   0.001425     43384000.0
                     4.0   0.001461     46788000.0
                     5.0   0.001654     52858000.0
                     6.0   0.001655     56240000.0
                     7.0   0.001830     76279000.0
                     8.0   0.002125     81737562.0
                     9.0   0.002151     93905562.0
                     10.0  0.002260     99950562.0
                     11.0  0.002548    111403562.0
                     12.0  0.002746    123699562.0
                     13.0  0.002924    141936562.0
                     14.0  0.003286    151695562.0
                     15.0  0.003480    159830562.0
                     16.0  0.003796    165780562.0
                     17.0  0.004269    171318562.0
                     18.0  0.004530    178955562.0
                     19.0  0.004864    194268562.0
                     20.0  0.005345    201885562.0
                     21.0  0.005726    208933562.0
                                          ...
the bug stops here.  4.0   0.009068     61187000.0
                           0.009203     61187000.0
                           0.177029     48799000.0
                     5.0   0.012969     66805000.0
                           0.013059     66805000.0
                           0.222439     66805000.0
                     6.0   0.044622     72263562.0
                           0.046265     72263562.0
                           0.266747     71283000.0
                     7.0   0.354102     74921000.0
                           0.458898     84431562.0
                           0.522351     84431562.0
                     8.0   0.370158     87009562.0
                     9.0   0.497110     97871000.0
                     10.0  0.465340    104507562.0
                     11.0  0.568832    116803562.0
                     12.0  0.638584    135040562.0
                     13.0  0.598098    144799562.0
                     14.0  0.618196    152934562.0
                     15.0  0.815469    154020562.0
                     16.0  0.763663    159015562.0
                     17.0  0.894719    166063562.0
                     18.0  0.811461    173680562.0
                     19.0  0.843810    181317562.0
                     20.0  0.907976    196630562.0
                     21.0  0.939482    202168562.0
                     22.0  0.982326    206653562.0
                     23.0  1.026217    210642562.0
                     24.0  1.085980    213881562.0
                     25.0  1.092079    215232562.0
Name: output, Length: 1554, dtype: float64

In [89]:
next_level = functions_df[functions_df['function'] == 'new_nation_with_pop']

In [90]:
next_level.sort_values(by = ['output', 'time'], ascending=[False, True]).drop_duplicates(['team'])

,Date,team,function,valid_error,n,output,time,exceptions
1086,2018-08-05 15:44:11,the bug stops here.,new_nation_with_pop,valid,265.0,39.0,0.017014,NaN
2336,2018-08-06 00:00:09,Rick and Morty,new_nation_with_pop,valid,265.0,39.0,0.017041,NaN
4061,2018-08-07 04:10:10,United Misfits,new_nation_with_pop,valid,265.0,39.0,0.017229,NaN
1349,2018-08-05 16:17:37,Glass Class,new_nation_with_pop,valid,265.0,39.0,0.017332,NaN
4369,2018-08-07 10:15:07,H.Y. Brothers,new_nation_with_pop,valid,265.0,39.0,0.017416,NaN
3191,2018-08-06 14:25:09,hehesb,new_nation_with_pop,valid,265.0,39.0,0.017430,NaN
178,2018-08-05 15:01:08,"Python, do you love me?",new_nation_with_pop,valid,265.0,39.0,0.017474,NaN
3791,2018-08-06 20:30:08,Tinker Tailor Soldier Spy,new_nation_with_pop,valid,265.0,39.0,0.017560,NaN
73,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,265.0,39.0,0.017561,NaN
2409,2018-08-06 01:30:08,UnitedStates.split(),new_nation_with_pop,valid,265.0,39.0,0.017705,NaN
1445,2018-08-05 16:17:48,OpaqueRat,new_nation_with_pop,valid,265.0,39.0,0.017718,NaN
1566,2018-08-05 16:17:59,Back in the US,new_nation_with_pop,valid,265.0,39.0,0.017780,NaN
2288,2018-08-05 21:50:08,OP GG,new_nation_with_pop,valid,265.0,39.0,0.017828,NaN
3927,2018-08-07 02:00:09,SwatKats,new_nation_with_pop,valid,265.0,39.0,0.017883,NaN
749,2018-08-05 15:05:11,Carpe Diem,new_nation_with_pop,valid,265.0,39.0,0.018189,NaN
898,2018-08-05 15:05:19,Flying Dutchman,new_nation_with_pop,valid,265.0,39.0,0.018523,NaN
251,2018-08-05 15:01:09,You can have it,new_nation_with_pop,valid,265.0,39.0,0.018551,NaN
3988,2018-08-07 04:00:10,sunkenstates,new_nation_with_pop,valid,265.0,39.0,0.018721,NaN
1397,2018-08-05 16:17:42,The United States of Westeros,new_nation_with_pop,valid,265.0,39.0,0.018727,NaN
1664,2018-08-05 17:30:08,Thebutterflyeffect,new_nation_with_pop,valid,265.0,39.0,0.019176,NaN
1943,2018-08-05 19:05:09,Deadpool,new_nation_with_pop,valid,265.0,39.0,0.021552,NaN
3118,2018-08-06 14:11:48,State of Mind,new_nation_with_pop,valid,265.0,39.0,0.023079,NaN
2112,2018-08-05 20:45:10,Game of States,new_nation_with_pop,valid,265.0,39.0,0.098320,NaN
2672,2018-08-06 09:55:10,We Were (Data)Framed!,new_nation_with_pop,valid,265.0,39.0,0.098610,NaN
2903,2018-08-06 13:30:14,Jatt United,new_nation_with_pop,valid,265.0,39.0,0.289013,NaN
3572,2018-08-06 18:30:47,random2,new_nation_with_pop,valid,265.0,39.0,0.351255,NaN
579,2018-08-05 15:04:54,The Republic of Texas,new_nation_with_pop,valid,265.0,39.0,0.826186,NaN
412,2018-08-05 15:03:13,Manifest Destiny,new_nation_with_pop,valid,265.0,39.0,1.456194,NaN
3447,2018-08-06 17:03:56,Need for Succeed,new_nation_with_pop,valid,240.0,28.0,4.827081,NaN
480,2018-08-05 15:04:35,asdfghjkl,new_nation_with_pop,valid,240.0,28.0,4.933786,NaN
964,2018-08-05 15:06:58,Mavericks,new_nation_with_pop,valid,155.0,14.0,4.840084,NaN
2588,2018-08-06 09:44:47,A_team,new_nation_with_pop,valid,100.0,9.0,0.417509,NaN
2062,2018-08-05 20:40:23,What If Analytics,new_nation_with_pop,valid,85.0,8.0,4.468393,NaN
1288,2018-08-05 16:17:13,Cession,new_nation_with_pop,valid,75.0,7.0,1.674284,NaN
330,2018-08-05 15:02:08,ChickenRun,new_nation_with_pop,valid,70.0,6.0,3.143130,NaN
2214,2018-08-05 21:35:19,PH 10.0,new_nation_with_pop,valid,70.0,6.0,3.262063,NaN
3878,2018-08-07 01:40:19,Speed Fiends,new_nation_with_pop,valid,65.0,5.0,1.058173,NaN
2547,2018-08-06 09:41:20,America States United,new_nation_with_pop,valid,40.0,3.0,0.474542,NaN
303,2018-08-05 15:01:43,USS Parche,new_nation_with_pop,invalid,30.0,NaN,0.001427,NaN
679,2018-08-05 15:05:07,CIA Operative #6,new_nation_with_pop,error,NaN,NaN,NaN,exception: 'tuple' object has no attribute 'ap...
849,2018-08-05 15:05:15,Border Horsemen,new_nation_with_pop,error,NaN,NaN,NaN,"exception: ('Connectivity is undefined ', 'for..."

In [96]:
test_df.groupby('team').max()

,Date,function,valid_error,n,output,time
team,,,,,,
A_team,2018-08-06 09:45:02,new_nation_n_states,valid,10.0,101929562.0,3.488890
Back in the US,2018-08-05 16:17:59,new_nation_n_states,valid,25.0,228949562.0,0.007732
Border Horsemen,2018-08-05 20:15:09,new_nation_n_states,valid,2.0,0.0,0.003296
CIA Operative #6,2018-08-05 19:15:12,new_nation_n_states,valid,21.0,208933562.0,0.330160
Carpe Diem,2018-08-05 15:05:11,new_nation_n_states,valid,25.0,228949562.0,0.008177
Cession,2018-08-05 16:17:30,new_nation_n_states,valid,11.0,118238562.0,4.063881
ChickenRun,2018-08-05 15:02:03,new_nation_n_states,valid,7.0,72263562.0,0.836097
Deadpool,2018-08-06 17:55:45,new_nation_n_states,valid,25.0,228949562.0,4.320051
Divide and conquer,2018-08-06 10:05:14,new_nation_n_states,valid,25.0,215577562.0,0.529525
Flying Dutchman,2018-08-05 15:05:19,new_nation_n_states,valid,25.0,193308562.0,0.008054
Game of States,2018-08-05 20:45:10,new_nation_n_states,valid,25.0,228949562.0,0.042429
Give Me Liberty or Give Me Death!,2018-08-05 15:02:14,new_nation_n_states,valid,25.0,196986562.0,0.041900
H.Y. Brothers,2018-08-07 11:35:09,new_nation_n_states,valid,25.0,228949562.0,1.564854
Jatt United,2018-08-06 16:31:15,new_nation_n_states,valid,23.0,214990562.0,4.774439
Manifest Destiny,2018-08-05 15:03:30,new_nation_n_states,valid,25.0,228949562.0,1.904242
Mavericks,2018-08-07 10:51:32,new_nation_n_states,valid,15.0,158714562.0,4.822223
Need for Succeed,2018-08-06 17:02:59,new_nation_n_states,valid,25.0,228949562.0,0.494199
OP GG,2018-08-05 21:50:08,new_nation_n_states,valid,25.0,193308562.0,0.007510
OpaqueRat,2018-08-06 14:45:16,new_nation_n_states,valid,25.0,193308562.0,2.210340
PH 10.0,2018-08-07 02:45:27,new_nation_n_states,valid,12.0,132462562.0,4.228241
"Python, do you love me?",2018-08-05 15:01:09,new_nation_n_states,valid,25.0,193308562.0,0.007619
Pyxit,2018-08-05 19:30:14,new_nation_n_states,valid,7.0,72263562.0,0.623212
Rick and Morty,2018-08-06 00:05:09,new_nation_n_states,valid,25.0,34888000.0,0.024021
Speed Fiends,2018-08-07 01:40:17,new_nation_n_states,valid,8.0,84431562.0,3.821910
State of Mind,2018-08-06 14:11:47,new_nation_n_states,valid,25.0,224464562.0,0.121120
SwatKats,2018-08-05 15:00:48,new_nation_n_states,valid,7.0,72263562.0,2.451777
The Republic of Texas,2018-08-07 09:21:58,new_nation_n_states,valid,25.0,228949562.0,4.651572
The United States of Westeros,2018-08-05 15:01:33,new_nation_n_states,valid,25.0,228949562.0,0.009618
Thebutterflyeffect,2018-08-05 17:20:08,new_nation_n_states,valid,25.0,228949562.0,0.008488
TimeWizards,2018-08-07 07:50:07,new_nation_n_states,error,NaN,NaN,NaN
Tinker Tailor Soldier Spy,2018-08-05 15:04:57,new_nation_n_states,valid,25.0,228949562.0,0.329477
United Misfits,2018-08-07 04:10:10,new_nation_n_states,valid,25.0,224986562.0,0.321719
UnitedStates.split(),2018-08-06 01:30:09,new_nation_n_states,valid,25.0,228949562.0,0.653950
Uptown funk you up,2018-08-06 14:15:35,new_nation_n_states,valid,25.0,164575562.0,2.368314
We Were (Data)Framed!,2018-08-06 09:45:09,new_nation_n_states,valid,25.0,228949562.0,0.065889
What If Analytics,2018-08-05 20:40:16,new_nation_n_states,valid,9.0,92253000.0,3.507000
You can have it,2018-08-05 15:01:10,new_nation_n_states,valid,25.0,228949562.0,0.007592
asdfghjkl,2018-08-05 15:04:43,new_nation_n_states,valid,25.0,228949562.0,0.337887
hehesb,2018-08-06 15:50:38,new_nation_n_states,valid,25.0,228949562.0,0.580381
random2,2018-08-06 19:05:54,new_nation_n_states,valid,25.0,228949562.0,1.734203
sunkenstates,2018-08-05 15:05:13,new_nation_n_states,valid,25.0,228949562.0,0.009629
the bug stops here.,2018-08-05 19:45:15,new_nation_n_states,valid,25.0,215232562.0,1.092079

In [98]:
test_df.sort_values(by = ['output', 'time'], ascending=[False, True]).drop_duplicates(['team'])

,Date,team,function,valid_error,n,output,time,exceptions
276,2018-08-05 15:01:10,You can have it,new_nation_n_states,valid,25.0,228949562.0,0.007592,NaN
3216,2018-08-06 14:25:09,hehesb,new_nation_n_states,valid,25.0,228949562.0,0.007642,NaN
1591,2018-08-05 16:17:59,Back in the US,new_nation_n_states,valid,25.0,228949562.0,0.007732,NaN
774,2018-08-05 15:05:11,Carpe Diem,new_nation_n_states,valid,25.0,228949562.0,0.008177,NaN
2434,2018-08-06 01:30:09,UnitedStates.split(),new_nation_n_states,valid,25.0,228949562.0,0.008204,NaN
4549,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,25.0,228949562.0,0.008280,NaN
1616,2018-08-05 17:20:08,Thebutterflyeffect,new_nation_n_states,valid,25.0,228949562.0,0.008488,NaN
531,2018-08-05 15:04:44,The Republic of Texas,new_nation_n_states,valid,25.0,228949562.0,0.008880,NaN
302,2018-08-05 15:01:33,The United States of Westeros,new_nation_n_states,valid,25.0,228949562.0,0.009618,NaN
847,2018-08-05 15:05:13,sunkenstates,new_nation_n_states,valid,25.0,228949562.0,0.009629,NaN
2471,2018-08-06 03:35:31,Deadpool,new_nation_n_states,valid,25.0,228949562.0,0.018710,NaN
2137,2018-08-05 20:45:10,Game of States,new_nation_n_states,valid,25.0,228949562.0,0.042429,NaN
2624,2018-08-06 09:45:09,We Were (Data)Framed!,new_nation_n_states,valid,25.0,228949562.0,0.064428,NaN
3524,2018-08-06 18:30:41,random2,new_nation_n_states,valid,25.0,228949562.0,0.210079,NaN
3404,2018-08-06 17:02:59,Need for Succeed,new_nation_n_states,valid,25.0,228949562.0,0.317997,NaN
604,2018-08-05 15:04:57,Tinker Tailor Soldier Spy,new_nation_n_states,valid,25.0,228949562.0,0.329477,NaN
506,2018-08-05 15:04:43,asdfghjkl,new_nation_n_states,valid,25.0,228949562.0,0.337887,NaN
437,2018-08-05 15:03:30,Manifest Destiny,new_nation_n_states,valid,25.0,228949562.0,1.904242,NaN
4013,2018-08-07 04:10:10,United Misfits,new_nation_n_states,valid,25.0,224986562.0,0.321719,NaN
3070,2018-08-06 14:11:47,State of Mind,new_nation_n_states,valid,25.0,224464562.0,0.121120,NaN
2745,2018-08-06 10:05:14,Divide and conquer,new_nation_n_states,valid,25.0,215577562.0,0.523813,NaN
2029,2018-08-05 19:35:24,the bug stops here.,new_nation_n_states,valid,25.0,215232562.0,1.092079,NaN
3378,2018-08-06 16:31:10,Jatt United,new_nation_n_states,valid,22.0,214990562.0,4.774439,NaN
1989,2018-08-05 19:15:12,CIA Operative #6,new_nation_n_states,valid,21.0,208933562.0,0.324481,NaN
356,2018-08-05 15:02:14,Give Me Liberty or Give Me Death!,new_nation_n_states,valid,25.0,196986562.0,0.041900,NaN
2240,2018-08-05 21:50:08,OP GG,new_nation_n_states,valid,25.0,193308562.0,0.007510,NaN
203,2018-08-05 15:01:09,"Python, do you love me?",new_nation_n_states,valid,25.0,193308562.0,0.007619,NaN
1470,2018-08-05 16:17:48,OpaqueRat,new_nation_n_states,valid,25.0,193308562.0,0.007799,NaN
923,2018-08-05 15:05:19,Flying Dutchman,new_nation_n_states,valid,25.0,193308562.0,0.008054,NaN
3143,2018-08-06 14:15:35,Uptown funk you up,new_nation_n_states,valid,25.0,164575562.0,2.368314,NaN
937,2018-08-05 15:05:51,Mavericks,new_nation_n_states,valid,14.0,158714562.0,4.822223,NaN
3938,2018-08-07 02:45:22,PH 10.0,new_nation_n_states,valid,11.0,132462562.0,4.228241,NaN
1300,2018-08-05 16:17:25,Cession,new_nation_n_states,valid,10.0,118238562.0,4.063881,NaN
2598,2018-08-06 09:44:57,A_team,new_nation_n_states,valid,9.0,101929562.0,3.488890,NaN
2049,2018-08-05 20:40:11,What If Analytics,new_nation_n_states,valid,8.0,92253000.0,1.963217,NaN
3869,2018-08-07 01:40:12,Speed Fiends,new_nation_n_states,valid,7.0,84431562.0,3.821910,NaN
2003,2018-08-05 19:30:09,Pyxit,new_nation_n_states,valid,6.0,72263562.0,0.598393,NaN
320,2018-08-05 15:01:58,ChickenRun,new_nation_n_states,valid,6.0,72263562.0,0.836097,NaN
108,2018-08-05 15:00:43,SwatKats,new_nation_n_states,valid,6.0,72263562.0,2.451777,NaN
2340,2018-08-06 00:05:08,Rick and Morty,new_nation_n_states,valid,4.0,34888000.0,0.010104,NaN
2039,2018-08-05 20:15:09,Border Horsemen,new_nation_n_states,valid,2.0,0.0,0.002691,NaN
4062,2018-08-07 07:50:07,TimeWizards,new_nation_n_states,error,NaN,NaN,NaN,exception: 'pop'

In [28]:
test_df.groupby(['team','function']).agg({'output': 'max'})

                                                            output
team                              function
A_team                            new_nation_n_states  101929562.0
Back in the US                    new_nation_n_states  228949562.0
Border Horsemen                   new_nation_n_states          0.0
CIA Operative #6                  new_nation_n_states  208933562.0
Carpe Diem                        new_nation_n_states  228949562.0
Cession                           new_nation_n_states  118238562.0
ChickenRun                        new_nation_n_states   72263562.0
Deadpool                          new_nation_n_states  228949562.0
Divide and conquer                new_nation_n_states  215577562.0
Flying Dutchman                   new_nation_n_states  193308562.0
Game of States                    new_nation_n_states  228949562.0
Give Me Liberty or Give Me Death! new_nation_n_states  196986562.0
H.Y. Brothers                     new_nation_n_states  228949562.0
Jatt United                       new_nation_n_states  214990562.0
Manifest Destiny                  new_nation_n_states  228949562.0
Mavericks                         new_nation_n_states  158714562.0
Need for Succeed                  new_nation_n_states  228949562.0
OP GG                             new_nation_n_states  193308562.0
OpaqueRat                         new_nation_n_states  193308562.0
PH 10.0                           new_nation_n_states  132462562.0
Python, do you love me?           new_nation_n_states  193308562.0
Pyxit                             new_nation_n_states   72263562.0
Rick and Morty                    new_nation_n_states   34888000.0
Speed Fiends                      new_nation_n_states   84431562.0
State of Mind                     new_nation_n_states  224464562.0
SwatKats                          new_nation_n_states   72263562.0
The Republic of Texas             new_nation_n_states  228949562.0
The United States of Westeros     new_nation_n_states  228949562.0
Thebutterflyeffect                new_nation_n_states  228949562.0
TimeWizards                       new_nation_n_states          NaN
Tinker Tailor Soldier Spy         new_nation_n_states  228949562.0
United Misfits                    new_nation_n_states  224986562.0
UnitedStates.split()              new_nation_n_states  228949562.0
Uptown funk you up                new_nation_n_states  164575562.0
We Were (Data)Framed!             new_nation_n_states  228949562.0
What If Analytics                 new_nation_n_states   92253000.0
You can have it                   new_nation_n_states  228949562.0
asdfghjkl                         new_nation_n_states  228949562.0
hehesb                            new_nation_n_states  228949562.0
random2                           new_nation_n_states  228949562.0
sunkenstates                      new_nation_n_states  228949562.0
the bug stops here.               new_nation_n_states  215232562.0

In [2]:
pd.read_csv('results.csv')

,2018-08-05 14:59:28,Speed Fiends,new_nation_with_pop,error,Unnamed: 4,Unnamed: 5,Unnamed: 6,exception: 'NoneType' object is not callable
0,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,1.0,34888000.0,0.022014,NaN
1,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,2.0,39325000.0,0.080588,NaN
2,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,3.0,44362000.0,0.029478,NaN
3,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,4.0,61187000.0,0.040840,NaN
4,2018-08-05 14:59:38,Divide and conquer,new_nation_n_states,valid,5.0,66805000.0,0.053688,NaN
5,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,6.0,71283000.0,0.068060,NaN
6,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,7.0,82195562.0,0.084373,NaN
7,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,8.0,92253000.0,0.099733,NaN
8,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,9.0,99870000.0,0.117431,NaN
9,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,10.0,116002562.0,0.136481,NaN
10,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,11.0,130226562.0,0.155175,NaN
11,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,12.0,139985562.0,0.176175,NaN
12,2018-08-05 14:59:39,Divide and conquer,new_nation_n_states,valid,13.0,148120562.0,0.197227,NaN
13,2018-08-05 14:59:40,Divide and conquer,new_nation_n_states,valid,14.0,154070562.0,0.220305,NaN
14,2018-08-05 14:59:40,Divide and conquer,new_nation_n_states,valid,15.0,157341562.0,0.243551,NaN
15,2018-08-05 14:59:40,Divide and conquer,new_nation_n_states,valid,16.0,161249562.0,0.267383,NaN
16,2018-08-05 14:59:41,Divide and conquer,new_nation_n_states,valid,17.0,168866562.0,0.293096,NaN
17,2018-08-05 14:59:41,Divide and conquer,new_nation_n_states,valid,18.0,176503562.0,0.319489,NaN
18,2018-08-05 14:59:41,Divide and conquer,new_nation_n_states,valid,19.0,191816562.0,0.346442,NaN
19,2018-08-05 14:59:42,Divide and conquer,new_nation_n_states,valid,20.0,197354562.0,0.416950,NaN
20,2018-08-05 14:59:42,Divide and conquer,new_nation_n_states,valid,21.0,201839562.0,0.404719,NaN
21,2018-08-05 14:59:42,Divide and conquer,new_nation_n_states,valid,22.0,205828562.0,0.434926,NaN
22,2018-08-05 14:59:43,Divide and conquer,new_nation_n_states,valid,23.0,211209562.0,0.466450,NaN
23,2018-08-05 14:59:43,Divide and conquer,new_nation_n_states,valid,24.0,213959562.0,0.498438,NaN
24,2018-08-05 14:59:44,Divide and conquer,new_nation_n_states,valid,25.0,215577562.0,0.529525,NaN
25,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,30.0,3.0,0.001554,NaN
26,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,35.0,4.0,0.001581,NaN
27,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,40.0,4.0,0.001468,NaN
28,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,45.0,5.0,0.001619,NaN
29,2018-08-05 14:59:44,Divide and conquer,new_nation_with_pop,valid,50.0,5.0,0.001546,NaN
...,...,...,...,...,...,...,...,...
4519,2018-08-07 11:35:09,H.Y. Brothers,new_nation_with_pop,valid,245.0,30.0,0.012637,NaN
4520,2018-08-07 11:35:09,H.Y. Brothers,new_nation_with_pop,valid,250.0,31.0,0.012614,NaN
4521,2018-08-07 11:35:09,H.Y. Brothers,new_nation_with_pop,valid,255.0,33.0,0.013594,NaN
4522,2018-08-07 11:35:09,H.Y. Brothers,new_nation_with_pop,valid,260.0,36.0,0.016824,NaN
4523,2018-08-07 11:35:09,H.Y. Brothers,new_nation_with_pop,valid,265.0,39.0,0.018690,NaN
4524,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,1.0,34888000.0,0.002305,NaN
4525,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,2.0,39325000.0,0.001829,NaN
4526,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,3.0,43384000.0,0.001844,NaN
4527,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,4.0,46788000.0,0.001778,NaN
4528,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,5.0,52858000.0,0.001908,NaN
4529,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,6.0,56240000.0,0.002139,NaN
4530,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,7.0,76279000.0,0.002187,NaN
4531,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,8.0,81737562.0,0.002206,NaN
4532,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,9.0,93905562.0,0.002541,NaN
4533,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,10.0,99950562.0,0.002809,NaN
4534,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,11.0,111403562.0,0.003000,NaN
4535,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,12.0,123699562.0,0.003083,NaN
4536,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,13.0,141936562.0,0.003686,NaN
4537,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,14.0,151695562.0,0.004302,NaN
4538,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,15.0,159830562.0,0.003763,NaN
4539,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,16.0,165780562.0,0.004551,NaN
4540,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,17.0,171318562.0,0.004586,NaN
4541,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,18.0,178955562.0,0.004993,NaN
4542,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,19.0,194268562.0,0.006043,NaN
4543,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,20.0,201885562.0,0.005905,NaN
4544,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,21.0,208933562.0,0.005944,NaN
4545,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,22.0,214314562.0,0.007922,NaN
4546,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,23.0,219636562.0,0.007003,NaN
4547,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,24.0,224464562.0,0.007412,NaN
4548,2018-08-07 11:35:09,H.Y. Brothers,new_nation_n_states,valid,25.0,228949562.0,0.008280,NaN

In [48]:
import pandas as pd
from pandas import Series, DataFrame
import datetime as dt

def adjusted_gdp(usgs, cpi, start, end):
    
    start = str(start)
    end = str(end)
    
    us_gdp = pd.read_csv(usgs, index_col = 0, parse_dates = True)
    us_gdp = us_gdp[start : end]
    us_gdp = us_gdp.shift(periods=1, freq='A', axis = 0)
    
    cpiai = pd.read_csv("cpiai.csv", index_col = 0, parse_dates = True)
    cpiai = cpiai[start : end]
    cpiai = cpiai.groupby(cpiai.index.year).mean()
    cpiai.index = pd.to_datetime(cpiai.index.astype(str))
    cpiai = cpiai.shift(periods=1, freq='A', axis = 0)
    
    adjusted_gdp = us_gdp.merge(cpiai, left_index=True, right_index=True)
    adjusted_gdp['adjusted_gdp'] = round(adjusted_gdp['GDP-US $ billion nominal'] / adjusted_gdp['Index'] * 100, 2)
    return adjusted_gdp['adjusted_gdp']

In [50]:
adjusted_gdp("usgs_1930_2014.csv", "cpiai.csv", 2002, 2014)

2002-12-31    6104.35
2003-12-31    6258.05
2004-12-31    6499.78
2005-12-31    6705.56
2006-12-31    6874.24
2007-12-31    6983.76
2008-12-31    6837.03
2009-12-31    6720.47
2010-12-31    6653.44
2011-12-31    6650.06
2012-12-31    6771.70
Freq: A-DEC, Name: adjusted_gdp, dtype: float64

In [101]:
functions_df['function'].value_counts()

new_nation_with_pop    2961
new_nation_n_states    1589
Name: function, dtype: int64

In [43]:
cpiai = pd.read_csv("cpiai.csv", index_col = 0, parse_dates = True)
cpiai = cpiai[str(start): str(end)]
cpiai = cpiai.groupby(cpiai.index.year).mean()
cpiai.index = pd.to_datetime(cpiai.index.astype(str))

cpiai = cpiai.shift(periods=1, freq='A', axis = 0)

adjusted_gdp = us_gdp.merge(cpiai, left_index=True, right_index=True)

adjusted_gdp['adjusted_gdp'] = round(adjusted_gdp['GDP-US $ billion nominal'] / adjusted_gdp['Index'] * 100, 2)

adjusted_gdp['adjusted_gdp']

In [45]:
adjusted_gdp = us_gdp.merge(cpiai, left_index=True, right_index=True)

adjusted_gdp['adjusted_gdp'] = round(adjusted_gdp['GDP-US $ billion nominal'] / adjusted_gdp['Index'] * 100, 2)

adjusted_gdp['adjusted_gdp']

2006-12-31    6874.24
2007-12-31    6983.76
2008-12-31    6837.03
Freq: A-DEC, Name: adjusted_gdp, dtype: float64

In [42]:
pd.to_datetime(cpiai.index.astype(str))

DatetimeIndex(['2006-01-01', '2007-01-01', '2008-01-01'], dtype='datetime64[ns]', freq=None)

In [6]:
adjusted_gdp = us_gdp.merge(cpiai, left_index=True, right_index=True)

In [7]:
adjusted_gdp['adjusted_gdp'] = round(adjusted_gdp['GDP-US $ billion nominal'] / adjusted_gdp['Index'] * 100, 2)

In [8]:
adjusted_gdp

,GDP-US $ billion nominal,Population-US million,Total Spending-total $ billion nominal,type,Index,Inflation,adjusted_gdp
2006,13857.9,298.145,4720.89,a,201.591667,0.210833,6874.24
2007,14480.3,300.807,4948.04,a,207.342417,0.334167,6983.76
2008,14720.3,303.492,5360.08,a,215.302500,0.012500,6837.03

In [9]:
adjusted_gdp['adjusted_gdp']

2006    6874.24
2007    6983.76
2008    6837.03
Freq: A-DEC, Name: adjusted_gdp, dtype: float64

In [299]:
cpiai = pd.read_csv("cpiai.csv", index_col = 0, parse_dates = True)#.to_period(freq='A-DEC')

cpiai = cpiai[str(start): str(end)]

In [308]:
cpiai.index.to_period('A')

PeriodIndex(['2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006',
             '2006', '2006', '2006', '2006', '2007', '2007', '2007', '2007',
             '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007',
             '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008',
             '2008', '2008', '2008', '2008'],
            dtype='period[A-DEC]', freq='A-DEC')

In [11]:
us_gdp = us_gdp[str(start) : str(end)]

In [33]:
us_gdp.shift(periods=1, freq='A', axis = 0).index

DatetimeIndex(['2006-12-31', '2007-12-31', '2008-12-31'], dtype='datetime64[ns]', freq='A-DEC')

In [232]:
test = pd.read_csv("usgs_1930_2014.csv", index_col = 0, parse_dates = True)#.to_period(freq = 'A')

In [246]:
test.index = test.index.astype(str)

In [265]:
index = pd.to_datetime(test.index, format = '%Y-%m-%d').to_period()

In [179]:
testdf = cpiai
testdf.index = testdf.index.astype(str)

In [188]:
pd.to_datetime(testdf.index).to_period(freq = 'A-DEC')

PeriodIndex(['2006', '2007', '2008'], dtype='period[A-DEC]', freq='A-DEC')

In [143]:
pd.to_datetime(cpiai.index, unit)

DatetimeIndex(['1970-01-01 00:00:00.002006', '1970-01-01 00:00:00.002007',
               '1970-01-01 00:00:00.002008'],
              dtype='datetime64[ns]', freq=None)

In [165]:
cpiai

        Index  Inflation
2006  198.300       0.76
2006  198.700       0.20
2006  199.800       0.55
2006  201.500       0.85
2006  202.500       0.50
2006  202.900       0.20
2006  203.500       0.30
2006  203.900       0.20
2006  202.900      -0.49
2006  201.800      -0.54
2006  201.500      -0.15
2006  201.800       0.15
2007  202.416       0.31
2007  203.499       0.54
2007  205.352       0.91
2007  206.686       0.65
2007  207.949       0.61
2007  208.352       0.19
2007  208.299      -0.03
2007  207.917      -0.18
2007  208.490       0.28
2007  208.936       0.21
2007  210.177       0.59
2007  210.036      -0.07
2008  211.080       0.50
2008  211.693       0.29
2008  213.528       0.87
2008  214.823       0.61
2008  216.632       0.84
2008  218.815       1.01
2008  219.964       0.53
2008  219.086      -0.40
2008  218.783      -0.14
2008  216.573      -1.01
2008  212.425      -1.92
2008  210.228      -1.03

In [159]:
cpiai

        Index  Inflation
2006  198.300       0.76
2006  198.700       0.20
2006  199.800       0.55
2006  201.500       0.85
2006  202.500       0.50
2006  202.900       0.20
2006  203.500       0.30
2006  203.900       0.20
2006  202.900      -0.49
2006  201.800      -0.54
2006  201.500      -0.15
2006  201.800       0.15
2007  202.416       0.31
2007  203.499       0.54
2007  205.352       0.91
2007  206.686       0.65
2007  207.949       0.61
2007  208.352       0.19
2007  208.299      -0.03
2007  207.917      -0.18
2007  208.490       0.28
2007  208.936       0.21
2007  210.177       0.59
2007  210.036      -0.07
2008  211.080       0.50
2008  211.693       0.29
2008  213.528       0.87
2008  214.823       0.61
2008  216.632       0.84
2008  218.815       1.01
2008  219.964       0.53
2008  219.086      -0.40
2008  218.783      -0.14
2008  216.573      -1.01
2008  212.425      -1.92
2008  210.228      -1.03

In [100]:

cpiai = pd.read_csv("cpiai.csv", index_col = 0, parse_dates = True).to_period(freq='A-DEC')

In [46]:
13857.9 / 6874

2.0159877800407333

In [71]:
13857.9 / 201.591667 * 100

6874.242475508673

In [74]:
cpiai['2007'].mean()

Index        207.342417
Inflation      0.334167
dtype: float64

In [75]:
14480.3 / 207.342417 * 100

6983.761552273214