In [1]:
%reload_ext ishbook
import pandas as pd
import numpy as np
import datetime as dt
import time
import iql
import plus
import re
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [14]:
%%ish

hosted_jobs = from hostedjobsnapshot 2016-10-31 2016-11-01 WHERE adMonthlyBudgetLocal != 0 campaignType = sponsored bidLocal != 0 status = active GROUP BY advertiserid SELECT atsjobid, adMonthlyBudgetLocal/100

Output = None

In [15]:
%%ish

dradis_jobs = from dradisjob 2016-10-31 2016-11-01 WHERE jobdatecreated >= 20161001 budgettype = MONTHLY status = ACTIVE adclickRev > 0 country in(us,ca) GROUP BY advid, atsjobid, jobdatecreated SELECT adclickRev

Output = None

In [16]:
hosted_jobs.head(10)

   advertiserid  atsjobid  adMonthlyBudgetLocal/100
0           806         2                     600.0
1           859        34                    1500.0
2          1344        58                   11600.0
3          1776        12                     900.0
4          1868        24                    4000.0
5          1947    121439                   81000.0
6          2307         1                     300.0
7          2325         1                     300.0
8          2491         4                     750.0
9          2656    174866                   22000.0

In [9]:
dradis_jobs.head(10)

    advid  atsjobid  jobdatecreated  adclickRev
0   53144       121        20161001         250
1  116332        37        20161001          34
2  144061        21        20161001          63
3  221492       604        20161001         197
4  279335       632        20161001          39
5  279335       633        20161001          44
6  298444        44        20161001        2645
7  571429        59        20161001          43
8  648178         3        20161001          88
9  761565       168        20161001          58

In [17]:
print len(hosted_jobs)
print len(dradis_jobs)

586501
27407

In [19]:
dradis_jobs.merge(hosted_jobs, how = 'left', left_on = ['advid', 'atsjobid'], right_on = ['advertiserid', 'atsjobid']).dropna()

,advid,atsjobid,jobdatecreated,adclickRev,advertiserid,adMonthlyBudgetLocal/100
2,144061,21,20161001,63,144061.0,100.0
8,648178,3,20161001,88,648178.0,50.0
19,1603436,7,20161001,1409,1603436.0,350.0
25,2037082,5,20161001,232,2037082.0,350.0
27,2120838,7,20161001,20,2120838.0,50.0
29,2284525,5,20161001,9,2284525.0,100.0
30,2632809,33,20161001,17,2632809.0,350.0
31,2728108,3,20161001,55,2728108.0,50.0
33,2952538,5,20161001,15,2952538.0,350.0
37,3395452,22,20161001,47,3395452.0,300.0
61,6396354,7,20161001,396,6396354.0,350.0
62,6435392,3,20161001,523,6435392.0,250.0
63,6435445,3,20161001,72,6435445.0,50.0
67,7137431,2,20161001,269,7137431.0,350.0
72,8451190,3,20161001,24,8451190.0,50.0
94,549704,25,20161002,496,549704.0,250.0
104,1442509,15,20161002,48,1442509.0,100.0
105,1564777,13,20161002,138,1564777.0,50.0
111,2293267,3,20161002,164,2293267.0,200.0
113,2433110,6,20161002,323,2433110.0,100.0
119,3247768,21,20161002,177,3247768.0,200.0
120,3357366,5,20161002,343,3357366.0,150.0
133,6195621,8,20161002,109,6195621.0,200.0
146,8313065,1,20161002,27,8313065.0,100.0
147,8563111,6,20161002,4,8563111.0,50.0
148,9164405,1,20161002,17,9164405.0,100.0
150,9231884,1,20161002,166,9231884.0,50.0
159,20233,14,20161003,13,20233.0,450.0
166,46558,19,20161003,1034,46558.0,350.0
210,153459,17,20161003,219,153459.0,350.0
...,...,...,...,...,...,...
27288,8114827,3,20161031,327,8114827.0,250.0
27300,8209949,3,20161031,1129,8209949.0,350.0
27301,8267866,7,20161031,161,8267866.0,50.0
27309,8306888,2,20161031,161,8306888.0,50.0
27312,8327648,1,20161031,323,8327648.0,100.0
27338,8692647,2,20161031,39,8692647.0,100.0
27339,8695809,3,20161031,172,8695809.0,50.0
27340,8708616,2,20161031,307,8708616.0,350.0
27342,8726619,2,20161031,100,8726619.0,690.0
27344,8731615,2,20161031,629,8731615.0,100.0
27350,8905621,5,20161031,718,8905621.0,1000.0
27351,8948443,3,20161031,1290,8948443.0,400.0
27353,9028446,2,20161031,195,9028446.0,50.0
27363,9135274,1,20161031,1129,9135274.0,350.0
27364,9144121,3,20161031,484,9144121.0,150.0
27367,9261037,8,20161031,25259,9261037.0,1150.0
27368,9269353,2,20161031,161,9269353.0,50.0
27371,9285946,2,20161031,161,9285946.0,50.0
27381,9394985,2,20161031,76,9394985.0,350.0
27383,9450427,2,20161031,161,9450427.0,50.0
27385,9456310,3,20161031,161,9456310.0,50.0
27387,9486048,2,20161031,318,9486048.0,100.0
27391,9531477,3,20161031,458,9531477.0,300.0
27392,9536191,2,20161031,34,9536191.0,200.0
27393,9546163,2,20161031,1158,9546163.0,350.0
27398,9614965,1,20161031,53,9614965.0,670.0
27399,9615266,1,20161031,532,9615266.0,150.0
27400,9615332,1,20161031,259,9615332.0,75.0
27401,9616921,1,20161031,161,9616921.0,50.0
27406,9620798,1,20161031,236,9620798.0,200.0